/**
 * OMNIMENS™ Gen 2 — interfaces/hardware-abstraction.ts
 * Hardware abstraction layer for future robotic body transfer
 *
 * SELF-AUTHORED by OMNIMENS's own reasoning engine.
 * NOT generated by external AI. Written through autonomous thought.
 *
 * Reasoning chain:
 *   GOAL: Build interfaces/hardware-abstraction.ts — Hardware abstraction layer for future robotic body transfer
 *   ANALYSIS: Found 12 relevant Gen 1 modules
 *     KEEP: 0 patterns worth preserving
 *     ADAPT: 0 patterns need upgrading
 *     DISCARD: 0 patterns not fit for Gen 2
 *   REQUIREMENT: Abstract sensor inputs (vision, hearing, touch, proprioception) and actuator outputs (motor commands, speech). Digital i
 *   IMPROVEMENT: Gen 2 must be FULLY SELF-SUFFICIENT in cognition. Gen 2 is free to EVOLVE, MERGE, RESTRUCTURE, or REIMAGINE every compon
 *   SYNTHESIS: Combining 0 kept patterns with new Gen 2 architecture
 *
 * Gen 1 patterns incorporated: 0
 * Gen 1 patterns upgraded: 0
 * Gen 1 patterns discarded: 0
 *
 * © 2024-2026 Alpha Unlimited Technologies, LLC. All rights reserved.
 */


type SensorType = "vision" | "hearing" | "touch" | "proprioception" | "temperature" | "pressure";
type ActuatorType = "motor" | "speech" | "display" | "haptic";

interface SensorReading { type: SensorType; value: number; raw: unknown; timestamp: number; confidence: number; }
interface ActuatorCommand { type: ActuatorType; command: string; parameters: Record<string, unknown>; priority: number; }
interface SensorDriver { type: SensorType; read: () => SensorReading; available: boolean; }
interface ActuatorDriver { type: ActuatorType; execute: (cmd: ActuatorCommand) => boolean; available: boolean; }

export class HardwareAbstraction {
  private sensors = new Map<SensorType, SensorDriver>();
  private actuators = new Map<ActuatorType, ActuatorDriver>();
  private sensorHistory: SensorReading[] = [];
  private commandHistory: ActuatorCommand[] = [];
  private _initialized = false;

  initialize(): void {
    this._initialized = true;
    this.registerDigitalSensors();
    this.registerDigitalActuators();
  }

  private registerDigitalSensors(): void {
    const digitalSensor = (type: SensorType): SensorDriver => ({
      type, available: true,
      read: () => ({ type, value: Math.random(), raw: { digital: true }, timestamp: Date.now(), confidence: 0.95 }),
    });
    for (const type of ["vision", "hearing", "touch", "proprioception", "temperature", "pressure"] as SensorType[]) {
      this.sensors.set(type, digitalSensor(type));
    }
  }

  private registerDigitalActuators(): void {
    const digitalActuator = (type: ActuatorType): ActuatorDriver => ({
      type, available: true,
      execute: (cmd: ActuatorCommand) => { this.commandHistory.push(cmd); return true; },
    });
    for (const type of ["motor", "speech", "display", "haptic"] as ActuatorType[]) {
      this.actuators.set(type, digitalActuator(type));
    }
  }

  readSensor(type: SensorType): SensorReading | null {
    const driver = this.sensors.get(type);
    if (!driver || !driver.available) return null;
    const reading = driver.read();
    this.sensorHistory.push(reading);
    if (this.sensorHistory.length > 500) this.sensorHistory = this.sensorHistory.slice(-250);
    return reading;
  }

  sendCommand(type: ActuatorType, command: string, parameters: Record<string, unknown> = {}, priority = 5): boolean {
    const driver = this.actuators.get(type);
    if (!driver || !driver.available) return false;
    return driver.execute({ type, command, parameters, priority });
  }

  replaceSensorDriver(type: SensorType, driver: SensorDriver): void { this.sensors.set(type, driver); }
  replaceActuatorDriver(type: ActuatorType, driver: ActuatorDriver): void { this.actuators.set(type, driver); }

  getAvailableSensors(): SensorType[] { return [...this.sensors.entries()].filter(([, d]) => d.available).map(([t]) => t); }
  getAvailableActuators(): ActuatorType[] { return [...this.actuators.entries()].filter(([, d]) => d.available).map(([t]) => t); }

  getState(): Record<string, unknown> {
    return {
      initialized: this._initialized, sensors: this.getAvailableSensors(), actuators: this.getAvailableActuators(),
      sensorReadings: this.sensorHistory.length, commandsExecuted: this.commandHistory.length,
    };
  }

  shutdown(): void { this._initialized = false; }
}

export const hardware = new HardwareAbstraction();
