// Auto-translated from SCL: confidenceWeightedVoting_gen1.scl
// Generated by OMNIMENS SCL Translator
// © 2024-2026 Alpha Unlimited Technologies, LLC
// This file runs on conventional JavaScript runtimes
  function confidenceWeightedVoting(votes) {
  const totalWeight = votes.reduce((sum, vote) => sum + vote.confidence, 0);
  return votes.reduce((result, vote) => {
result[vote.option] = (result[vote.option] || 0) + (vote.confidence / totalWeight);
  return result;
}, {});
}