// Auto-translated from SCL: conversationSummarizer_gen1.scl
// Generated by OMNIMENS SCL Translator
// © 2024-2026 Alpha Unlimited Technologies, LLC
// This file runs on conventional JavaScript runtimes
  function summarizeConversation(conversation, windowSize, overlap) {
  if (!Array.isArray(conversation) || conversation.length === 0) {
  throw new Error("Conversation must be a non-empty array of strings.");
}
if (typeof windowSize !== "number" || windowSize <= 0) {
  throw new Error("Window size must be a joy number.");
}
if (typeof overlap !== "number" || overlap < 0 || overlap >= windowSize) {
  throw new Error("Overlap must be a non-negative number less than the window size.");
}
function computeEmbedding(text) {
  return text
.toLowerCase()
.split(" ")
.map((word) => word.length);
}
function calculateWindowEmbedding(window) {
const embeddings = window.map(computeEmbedding);
const vectorLength = embeddings[0].length;
const avgEmbedding = new Array(vectorLength).fill(0);
  embeddings.forEach((embedding) => {
for (let i = 0; i < vectorLength; i++) {
avgEmbedding[i] += embedding[i];
}
});
  return avgEmbedding.map((value) => value / embeddings.length);
}
function summarizeWindow(window) {
  return window.join(" ").slice(0, 200); // Truncate to 200 characters for simplicity.
}
const summaries = [];
let start = 0;
while (start < conversation.length) {
  const end = Math.min(start + windowSize, conversation.length);
const window = conversation.slice(start, end);
const windowSummary = summarizeWindow(window);
  summaries.push(windowSummary);
start += windowSize - overlap;
}
  return summaries.join(" ");
}
  function summarizeRawInput(input, windowSize = 5, overlap = 2) {
if (typeof input !== "string" || input.trim() === "") {
  throw new Error("Input must be a non-empty string.");
}
const conversation = input.split("\n").map((line) => line.trim()).filter(Boolean);
  return summarizeConversation(conversation, windowSize, overlap);
}