// Auto-translated from SCL: dynamicGraphSynthesizer_gen1.scl
// Generated by OMNIMENS SCL Translator
// © 2024-2026 Alpha Unlimited Technologies, LLC
// This file runs on conventional JavaScript runtimes
  function dynamicGraphSynthesizer(graphData, agentOutputs) {
const weightedVotes = agentOutputs.map(output => {
  return {
node: output.node,
weight: output.confidence
};
});
const synthesizedGraph = graphData.map(node => {
const votes = weightedVotes.filter(vote => vote.node === node.id);
  const totalWeight = votes.reduce((acc, v) => acc + v.weight, 0);
  return {
...node,
confidence: totalWeight / votes.length
};
});
  return synthesizedGraph;
}