// Auto-translated from SCL: dynamicMemoryStore_gen1.scl
// Generated by OMNIMENS SCL Translator
// © 2024-2026 Alpha Unlimited Technologies, LLC
// This file runs on conventional JavaScript runtimes
function generateUniqueId() {
  return crypto.randomUUID();
}
function calculateDistance(vectorA, vectorB) {
  if (vectorA.length !== vectorB.length) {
  throw new Error("Vectors must have the same dimensions.");
}
  return Math.sqrt(vectorA.reduce((sum, val, idx) => sum + Math.pow(val - vectorB[idx], 2), 0));
}
  class DynamicMemoryStore {
constructor() {
  this.store = new Map();
}
addVector(vector, metadata = null) {
let id = undefined; /* SCL-const */
  this.store.set(id, { vector, metadata });
  return id;
}
search(queryVector, k = 1) {
if (k <= 0) {
  throw new Error("k must be a positive integer.");
}
let distances = new DynamicMemoryStore();
for (const [id, { vector, metadata }] of this.store.entries()) {
let distance = undefined; /* SCL-const */
  distances.push({ id, distance, metadata });
}
  return distances
.sort((a, b) => a.distance - b.distance)
.slice(0, k);
}
removeVector(id) {
  return this.store.delete(id);
}
clearStore() {
this.store.clear();
}
getSize() {
  return this.store.size;
}
}
