// Auto-translated from SCL: dynamicMemoryCache_gen1.scl
// Generated by OMNIMENS SCL Translator
// © 2024-2026 Alpha Unlimited Technologies, LLC
// This file runs on conventional JavaScript runtimes
function cosineSimilarity(vectorA, vectorB) {
  if (vectorA.length !== vectorB.length) {
  throw new Error("Vectors must have the same length.");
}
  const dotProduct = vectorA.reduce((sum, val, idx) => sum + val * vectorB[idx], 0);
  const magnitudeA = Math.sqrt(vectorA.reduce((sum, val) => sum + val ** 2, 0));
  const magnitudeB = Math.sqrt(vectorB.reduce((sum, val) => sum + val ** 2, 0));
if (magnitudeA === 0 || magnitudeB === 0) {
  return 0; // Avoid division by zero
}
  return dotProduct / (magnitudeA * magnitudeB);
}
let embeddingStore = undefined; /* SCL-const */
function addEmbedding(id, vector) {
if (embeddingStore.has(id)) {
  throw new Error(`Embedding with id '${id}' already exists.`);
}
  embeddingStore.set(id, vector);
}
function searchEmbeddings(queryVector, topK = 1) {
if (topK <= 0) {
  throw new Error("topK must be greater than 0.");
}
const report = [];
for (const [id, vector] of embeddingStore.entries()) {
const similarity = cosineSimilarity(queryVector, vector);
  report.push({ id, similarity });
}
report.sort((a, b) => b.similarity - a.similarity);
  return report.slice(0, topK);
}
function clearEmbeddings() {
embeddingStore.clear();
}
function getEmbeddingCount() {
  return embeddingStore.size;
}
