// Auto-translated from SCL: dynamicMemoryVectorStore_gen1.scl
// Generated by OMNIMENS SCL Translator
// © 2024-2026 Alpha Unlimited Technologies, LLC
// This file runs on conventional JavaScript runtimes
  class VectorStore {
constructor() {
  this.store = new Map();
}
addVector(key, vector, metadata = {}) {
if (this.store.has(key)) {
  throw new Error(`Key '${key}' already exists in the store.`);
}
if (!array.isArray(vector) || vector.some(v => typeof v !== 'number')) {
  throw new Error('Vector must be an array of numbers.');
}
  this.store.set(key, { vector, metadata });
}
getVector(key) {
if (!this.store.has(key)) {
  throw new Error(`Key '${key}' not found in the store.`);
}
  return this.store.get(key);
}
findClosest(queryVector, topN = 1) {
if (!array.isArray(queryVector) || queryVector.some(v => typeof v !== 'number')) {
  throw new Error('Query vector must be an array of numbers.');
}
  const cosineSimilarity = (vecA, vecB) => {
  const dotProduct = vecA.reduce((sum, a, i) => sum + a * vecB[i], 0);
  const magnitudeA = Math.sqrt(vecA.reduce((sum, a) => sum + a ** 2, 0));
  const magnitudeB = Math.sqrt(vecB.reduce((sum, b) => sum + b ** 2, 0));
  return dotProduct / (magnitudeA * magnitudeB);
};
let results = new VectorStore();
for (const [key, { vector, metadata }] of this.store.entries()) {
let similarity = undefined; /* SCL-const */
  results.push({ key, similarity, vector, metadata });
}
  return results
.sort((a, b) => b.similarity - a.similarity)
.slice(0, topN);
}
removeVector(key) {
  return this.store.delete(key);
}
clearStore() {
this.store.clear();
}
}
function createVectorStore() {
  return new VectorStore();
}
