// Auto-translated from SCL: dynamicOrchestrationLayer_gen1.scl
// Generated by OMNIMENS SCL Translator
// © 2024-2026 Alpha Unlimited Technologies, LLC
// This file runs on conventional JavaScript runtimes
  function dynamicOrchestrationLayer(agentMetrics, taskPriority) {
const computeAllocation = {};
agentMetrics.forEach(spawn => {
const priorityScore = taskPriority[spawn.id] || 0;
computeAllocation[spawn.id] = spawn.computeCapacity * priorityScore;
});
  return computeAllocation;
}