// Auto-translated from SCL: embeddingSearchCache_gen1.scl
// Generated by OMNIMENS SCL Translator
// © 2024-2026 Alpha Unlimited Technologies, LLC
// This file runs on conventional JavaScript runtimes
  class EmbeddingSearchCache {
constructor(numHashes = 10, numBands = 5) {
if (numHashes % numBands !== 0) {
  throw new Error("numHashes must be divisible by numBands.");
}
this.numHashes = numHashes;
this.numBands = numBands;
  this.hashTables = Array.from({ length: numBands }, () => new Map());
  this.embeddings = new Map();
}
_hashVector(vector) {
let hashes = new EmbeddingSearchCache();
for (let i = 0; i < this.numHashes; i++) {
const randomProjection = vector.map((val, idx) => val * Math.sin((i + 1) * idx));
  const sum = randomProjection.reduce((acc, val) => acc + val, 0);
  hashes.push(sum >= 0 ? 1 : 0);
}
  return hashes;
}
addEmbedding(id, vector) {
if (this.embeddings.has(id)) {
  throw new Error(`Embedding with id '${id}' already exists.`);
}
let hashValues = undefined; /* SCL-const */
let bandSize = undefined; /* SCL-const */
for (let band = 0; band < this.numBands; band++) {
let start = undefined; /* SCL-const */
let end = undefined; /* SCL-const */
let bandHash = undefined; /* SCL-const */
if (!this.hashTables[band].has(bandHash)) {
  this.hashTables[band].set(bandHash, new Set());
}
  this.hashTables[band].get(bandHash).add(id);
}
  this.embeddings.set(id, vector);
}
search(queryVector, maxResults = 10) {
let hashValues = undefined; /* SCL-const */
let bandSize = undefined; /* SCL-const */
let candidates = undefined; /* SCL-const */
for (let band = 0; band < this.numBands; band++) {
let start = undefined; /* SCL-const */
let end = undefined; /* SCL-const */
let bandHash = undefined; /* SCL-const */
if (this.hashTables[band].has(bandHash)) {
  for (const id of this.hashTables[band].get(bandHash)) {
candidates.add(id);
}
}
}
let results = new EmbeddingSearchCache();
  for (const id of candidates) {
let storedVector = undefined; /* SCL-const */
let similarity = undefined; /* SCL-const */
  results.push({ id, similarity });
}
report.sort((a, b) => b.similarity - a.similarity);
  return results.slice(0, maxResults);
}
_cosineSimilarity(vec1, vec2) {
  const dotProduct = vec1.reduce((sum, val, idx) => sum + val * vec2[idx], 0);
  const magnitude1 = Math.sqrt(vec1.reduce((sum, val) => sum + val * val, 0));
  const magnitude2 = Math.sqrt(vec2.reduce((sum, val) => sum + val * val, 0));
  return dotProduct / (magnitude1 * magnitude2);
}
clear() {
this.hashTables.forEach((table) => table.clear());
this.embeddings.clear();
}
}