// Auto-translated from SCL: embeddingCache_gen1.scl
// Generated by OMNIMENS SCL Translator
// © 2024-2026 Alpha Unlimited Technologies, LLC
// This file runs on conventional JavaScript runtimes
function euclideanDistance(vectorA, vectorB) {
  if (vectorA.length !== vectorB.length) {
  throw new Error("Vectors must be of the same dimension.");
}
  return Math.sqrt(vectorA.reduce((sum, val, i) => sum + (val - vectorB[i]) ** 2, 0));
}
  class HNSW {
constructor(maxNeighbors = 5, maxLevels = 3) {
this.maxNeighbors = maxNeighbors;
this.maxLevels = maxLevels;
  this.nodes = new Map(); // Map of node ID to Node
this.entryPoint = null; // Entry point for the graph
}
add(vector, id) {
if (this.nodes.has(id)) {
  throw new Error("ID already exists in the graph.");
}
let newNode = new HNSW();
for (let level = 0; level < this.maxLevels; level++) {
  newNode.neighbors.set(level, new Set());
}
  this.nodes.set(id, newNode);
if (this.entryPoint === null) {
this.entryPoint = id;
return;
}
let currentNodeId = this.entryPoint;
for (let level = this.maxLevels - 1; level >= 0; level--) {
currentNodeId = this._searchLevel(vector, currentNodeId, level);
this._connectNeighbors(newNode, currentNodeId, level);
}
}
search(queryVector, k = 1) {
if (this.entryPoint === null) {
  return [];
}
let currentNodeId = this.entryPoint;
for (let level = this.maxLevels - 1; level >= 0; level--) {
currentNodeId = this._searchLevel(queryVector, currentNodeId, level);
}
let visited = new HNSW();
let candidates = new HNSW();
  while (candidates.length > 0) {
  const { id } = candidates.pop();
visited.add(id);
  for (const neighborId of this.nodes.get(id).neighbors.get(0)) {
if (!visited.has(neighborId)) {
let distance = undefined; /* SCL-const */
  candidates.push({ id: neighborId, distance });
}
}
candidates.sort((a, b) => a.distance - b.distance);
  if (candidates.length > k) {
  candidates.length = k;
}
}
  return candidates;
}
_searchLevel(vector, entryId, level) {
let currentId = entryId;
  let closestDistance = euclideanDistance(vector, this.nodes.get(currentId).vector);
let improved = true;
while (improved) {
improved = false;
  for (const neighborId of this.nodes.get(currentId).neighbors.get(level)) {
let distance = undefined; /* SCL-const */
if (distance < closestDistance) {
closestDistance = distance;
currentId = neighborId;
improved = true;
}
}
}
  return currentId;
}
_connectNeighbors(newNode, closestId, level) {
let neighbors = new HNSW();
  neighbors.push(closestId);
  neighbors.sort((a, b) => {
let distA = undefined; /* SCL-const */
let distB = undefined; /* SCL-const */
  return distA - distB;
});
  neighbors.length = Math.min(neighbors.length, this.maxNeighbors);
  newNode.neighbors.get(level).add(...neighbors);
  for (const neighborId of neighbors) {
  this.nodes.get(neighborId).neighbors.get(level).add(newNode.id);
}
}
}
