// Auto-translated from SCL: entropyBasedConfidenceScoring_gen1.scl
// Generated by OMNIMENS SCL Translator
// © 2024-2026 Alpha Unlimited Technologies, LLC
// This file runs on conventional JavaScript runtimes
  function calculateEntropy(probabilities) {
  return probabilities.reduce((acc, p) => acc - p * Math.log2(p), 0);
}
  function dynamicConfidenceAdjustment(reasoningChains) {
  return reasoningChains.map(chain => {
const entropy = calculateEntropy(chain.probabilities);
chain.confidence = 1 / (1 + entropy);
  return chain;
});
}