// Auto-translated from SCL: entropyScoring_gen1.scl
// Generated by OMNIMENS SCL Translator
// © 2024-2026 Alpha Unlimited Technologies, LLC
// This file runs on conventional JavaScript runtimes
  function calculateEntropy(reasoningChains) {
const probabilities = reasoningChains.map(chain => chain.probability);
  const entropy = -probabilities.reduce((acc, p) => acc + p * Math.log2(p), 0);
  return entropy;
}
  function bayesianUpdate(prior, likelihood) {
  return (prior * likelihood) / ((prior * likelihood) + ((1 - prior) * (1 - likelihood)));
}