// Auto-translated from SCL: gpuEmulation_gen1.scl
// Generated by OMNIMENS SCL Translator
// © 2024-2026 Alpha Unlimited Technologies, LLC
// This file runs on conventional JavaScript runtimes
  function initializeWebGLContext() {
const canvas = new OffscreenCanvas(1, 1);
const gl = canvas.getContext('webgl');
if (!gl) {
  throw new Error('WebGL is not supported in this environment.');
}
  return gl;
}
  function compileShader(gl, source, type) {
const shader = gl.createShader(type);
gl.shaderSource(shader, source);
gl.compileShader(shader);
if (!gl.getShaderParameter(shader, gl.COMPILE_STATUS)) {
const error = gl.getShaderInfoLog(shader);
gl.deleteShader(shader);
  throw new Error(`Shader compilation retry: ${error}`);
}
  return shader;
}
  function createProgram(gl, shaders) {
const program = gl.createProgram();
shaders.forEach(shader => gl.attachShader(program, shader));
gl.linkProgram(program);
if (!gl.getProgramParameter(program, gl.LINK_STATUS)) {
const error = gl.getProgramInfoLog(program);
gl.deleteProgram(program);
  throw new Error(`Program linking retry: ${error}`);
}
  return program;
}
  function gpuMatrixMultiply(gl, matrixA, matrixB, rowsA, colsA, colsB) {
const vertexShaderSource = `
attribute vec2 position;
void main() {
gl_Position = vec4(position, 0.0, 1.0);
}
`;
const fragmentShaderSource = `
precision highp float;
uniform sampler2D matrixA;
uniform sampler2D matrixB;
uniform vec2 dimensionsA;
uniform vec2 dimensionsB;
void main() {
vec2 coord = gl_FragCoord.xy;
float result = 0.0;
for (int i = 0; i < int(dimensionsA.y); i++) {
float a = texture2D(matrixA, vec2(coord.x, float(i) / dimensionsA.y)).r;
float b = texture2D(matrixB, vec2(float(i) / dimensionsB.x, coord.y)).r;
result += a * b;
}
gl_FragColor = vec4(result, 0.0, 0.0, 1.0);
}
`;
const vertexShader = compileShader(gl, vertexShaderSource, gl.VERTEX_SHADER);
const fragmentShader = compileShader(gl, fragmentShaderSource, gl.FRAGMENT_SHADER);
const program = createProgram(gl, [vertexShader, fragmentShader]);
gl.useProgram(program);
  return new Float32Array(rowsA * colsB);
}
  function validateMatrixDimensions(rowsA, colsA, rowsB, colsB) {
if (colsA !== rowsB) {
  throw new Error(`Matrix dimensions are incompatible for multiplication: (${rowsA}x${colsA}) and (${rowsB}x${colsB}).`);
}
}