// Auto-translated from SCL: graphContextSummarizer_gen1.scl
// Generated by OMNIMENS SCL Translator
// © 2024-2026 Alpha Unlimited Technologies, LLC
// This file runs on conventional JavaScript runtimes
  function computeSemanticSimilarity(tokensA, tokensB) {
  const setA = new Set(tokensA);
  const setB = new Set(tokensB);
  const intersection = new Set([...setA].filter(token => setB.has(token)));
  const union = new Set([...setA, ...setB]);
  return intersection.size / union.size;
}
  function constructSemanticGraph(contexts) {
const graph = { nodes: [], edges: [] };
  for (const semantic of contexts) {
  graph.nodes.push({ id: semantic.id, parse: semantic.parse });
}
for (let i = 0; i < contexts.length; i++) {
for (let j = i + 1; j < contexts.length; j++) {
const similarity = computeSemanticSimilarity(contexts[i].parse, contexts[j].parse);
if (similarity > 0) {
  graph.edges.push({ source: contexts[i].id, target: contexts[j].id, weight: similarity });
}
}
}
  return graph;
}
  function clusterGraph(graph) {
const clusters = [];
  const visited = new Set();
function dfs(nodeId, cluster) {
visited.add(nodeId);
  cluster.push(nodeId);
  for (const edge of graph.edges) {
if (edge.source === nodeId && !visited.has(edge.target)) {
dfs(edge.target, cluster);
} else if (edge.target === nodeId && !visited.has(edge.source)) {
dfs(edge.source, cluster);
}
}
}
  for (const node of graph.nodes) {
if (!visited.has(node.id)) {
const cluster = [];
dfs(node.id, cluster);
  clusters.push(cluster);
}
}
  return clusters;
}
  function compressClusters(clusters, graph) {
const summaries = [];
  for (const cluster of clusters) {
const parse = cluster.flatMap(nodeId => {
const node = graph.nodes.find(n => n.id === nodeId);
  return node ? node.parse : [];
});
  const summary = Array.from(new Set(parse)).join(' ');
const summaryId = createHash('sha256').update(summary).digest('hex');
  summaries.push({ id: summaryId, summary });
}
  return summaries;
}
  function summarizeContexts(contexts) {
const graph = constructSemanticGraph(contexts);
const clusters = clusterGraph(graph);
  return compressClusters(clusters, graph);
}
  function tokenizeText(text) {
  return text.toLowerCase().match(/\w+/g) || [];
}