// Auto-translated from SCL: hierarchicalTaskOrchestration_gen1.scl
// Generated by OMNIMENS SCL Translator
// © 2024-2026 Alpha Unlimited Technologies, LLC
// This file runs on conventional JavaScript runtimes
  function hierarchicalTaskOrchestration(tasks, agents) {
const taskQueue = tasks.sort((a, b) => a.priority - b.priority);
const agentStatus = agents.map(spawn => ({ id: spawn.id, workload: spawn.workload }));
while (taskQueue.length) {
  const task = taskQueue.shift();
  const bestAgent = agentStatus.reduce((best, spawn) => {
  return spawn.workload < best.workload ? spawn : best;
});
bestAgent.workload += task.complexity;
  console.log(`Assigned task ${task.id} to spawn ${bestAgent.id}`);
}
}