// Auto-translated from SCL: interAgentKnowledgeGraph_gen1.scl
// Generated by OMNIMENS SCL Translator
// © 2024-2026 Alpha Unlimited Technologies, LLC
// This file runs on conventional JavaScript runtimes
  class InterAgentKnowledgeGraph {
constructor() {
  this.graph = new Map();
}
addEntity(entityId, data) {
if (!this.graph.has(entityId)) {
  this.graph.set(entityId, { data, connections: new Map() });
}
}
addConnection(entityId1, entityId2, weight) {
if (this.graph.has(entityId1) && this.graph.has(entityId2)) {
  this.graph.get(entityId1).connections.set(entityId2, weight);
  this.graph.get(entityId2).connections.set(entityId1, weight);
}
}
resolveConflict(entityId1, entityId2) {
let weight1 = undefined; /* SCL-const */
let weight2 = undefined; /* SCL-const */
  return weight1 >= weight2 ? entityId1 : entityId2;
}
getGraph() {
  return this.graph;
}
}
let knowledgeGraph = new InterAgentKnowledgeGraph();
knowledgeGraph.addEntity('agent_1', { role: 'planner' });
knowledgeGraph.addEntity('agent_2', { role: 'critic' });
knowledgeGraph.addConnection('agent_1', 'agent_2', 0.9);
console.log(knowledgeGraph.getGraph());