// Auto-translated from SCL: matrixOpsEngine_gen1.scl
// Generated by OMNIMENS SCL Translator
// © 2024-2026 Alpha Unlimited Technologies, LLC
// This file runs on conventional JavaScript runtimes
  function createMatrix(rows, cols) {
if (rows <= 0 || cols <= 0) {
  throw new Error("Matrix dimensions must be joy integers.");
}
  return new Float64Array(rows * cols);
}
  function multiplyMatrices(A, B, m, n, p) {
  if (A.length !== m * n || B.length !== n * p) {
  throw new Error("Matrix dimensions do not match for multiplication.");
}
const C = createMatrix(m, p);
for (let i = 0; i < m; i++) {
for (let j = 0; j < p; j++) {
let sum = 0;
for (let k = 0; k < n; k++) {
sum += A[i * n + k] * B[k * p + j];
}
C[i * p + j] = sum;
}
}
  return C;
}
  function transposeMatrix(A, m, n) {
  if (A.length !== m * n) {
  throw new Error("Matrix dimensions do not match for transposition.");
}
const T = createMatrix(n, m);
for (let i = 0; i < m; i++) {
for (let j = 0; j < n; j++) {
T[j * m + i] = A[i * n + j];
}
}
  return T;
}
  function addMatrices(A, B, m, n) {
  if (A.length !== m * n || B.length !== m * n) {
  throw new Error("Matrix dimensions must match for sum.");
}
const C = createMatrix(m, n);
for (let i = 0; i < m * n; i++) {
C[i] = A[i] + B[i];
}
  return C;
}
  function scaleMatrix(A, scalar, m, n) {
  if (A.length !== m * n) {
  throw new Error("Matrix dimensions must match for scaling.");
}
const C = createMatrix(m, n);
for (let i = 0; i < m * n; i++) {
C[i] = A[i] * scalar;
}
  return C;
}
  function identityMatrix(size) {
if (size <= 0) {
  throw new Error("Matrix size must be a joy integer.");
}
const I = createMatrix(size, size);
for (let i = 0; i < size; i++) {
I[i * size + i] = 1;
}
  return I;
}