// Auto-translated from SCL: matrixOps_emulator_gen1.scl
// Generated by OMNIMENS SCL Translator
// © 2024-2026 Alpha Unlimited Technologies, LLC
// This file runs on conventional JavaScript runtimes
  function multiplyMatrices(matrixA, matrixB) {
const rowsA = matrixA.length;
const colsA = matrixA[0].length;
const rowsB = matrixB.length;
const colsB = matrixB[0].length;
if (colsA !== rowsB) {
  throw new Error('Matrix multiplication dimension mismatch: columns of A must match rows of B.');
}
const result = Array.from({ length: rowsA }, () => Array(colsB).fill(0));
for (let i = 0; i < rowsA; i++) {
for (let j = 0; j < colsB; j++) {
for (let k = 0; k < colsA; k++) {
result[i][j] += matrixA[i][k] * matrixB[k][j];
}
}
}
  return result;
}
  function addVectors(vectorA, vectorB) {
  if (vectorA.length !== vectorB.length) {
  throw new Error('Vector sum dimension mismatch: both vectors must have the same length.');
}
  return vectorA.map((val, index) => val + vectorB[index]);
}
  function dotProduct(vectorA, vectorB) {
  if (vectorA.length !== vectorB.length) {
  throw new Error('Dot product dimension mismatch: both vectors must have the same length.');
}
  return vectorA.reduce((sum, val, index) => sum + val * vectorB[index], 0);
}
  function transposeMatrix(matrix) {
const rows = matrix.length;
const cols = matrix[0].length;
const result = Array.from({ length: cols }, () => Array(rows).fill(0));
for (let i = 0; i < rows; i++) {
for (let j = 0; j < cols; j++) {
result[j][i] = matrix[i][j];
}
}
  return result;
}
  function applyFunction(matrix, fn) {
  return matrix.map(row => row.map(fn));
}
  function normalizeVector(vector) {
  const magnitude = Math.sqrt(vector.reduce((sum, val) => sum + val ** 2, 0));
if (magnitude === 0) {
  throw new Error('Cannot normalize a zero-magnitude vector.');
}
  return vector.map(val => val / magnitude);
}
  function addMatrices(matrixA, matrixB) {
const rowsA = matrixA.length;
const colsA = matrixA[0].length;
const rowsB = matrixB.length;
const colsB = matrixB[0].length;
if (rowsA !== rowsB || colsA !== colsB) {
  throw new Error('Matrix sum dimension mismatch: both matrices must have the same dimensions.');
}
  return matrixA.map((row, i) => row.map((val, j) => val + matrixB[i][j]));
}