// Auto-translated from SCL: memoryCachingLayer_gen1.scl
// Generated by OMNIMENS SCL Translator
// © 2024-2026 Alpha Unlimited Technologies, LLC
// This file runs on conventional JavaScript runtimes
let crypto = undefined; /* SCL-const */
let cache = undefined; /* SCL-const */
  function setCacheItem(key, vector, data) {
if (!Array.isArray(vector) || vector.some(isNaN)) {
  throw new Error('Vector must be an array of numbers.');
}
  cache.set(key, { key, vector, data });
}
  function getCacheItem(key) {
  return cache.get(key) || null;
}
  function clearCache() {
cache.clear();
}
function cosineSimilarity(vectorA, vectorB) {
  if (vectorA.length !== vectorB.length) {
  throw new Error('Vectors must be of the same length.');
}
  const dotProduct = vectorA.reduce((sum, val, i) => sum + val * vectorB[i], 0);
  const magnitudeA = Math.sqrt(vectorA.reduce((sum, val) => sum + val ** 2, 0));
  const magnitudeB = Math.sqrt(vectorB.reduce((sum, val) => sum + val ** 2, 0));
  return dotProduct / (magnitudeA * magnitudeB);
}
  function findSimilarItems(queryVector, topK = 5) {
if (!Array.isArray(queryVector) || queryVector.some(isNaN)) {
  throw new Error('Query vector must be an array of numbers.');
}
const similarities = [];
for (const { key, vector } of cache.values()) {
const similarity = cosineSimilarity(queryVector, vector);
  similarities.push({ key, similarity });
}
  return similarities
.sort((a, b) => b.similarity - a.similarity)
.slice(0, topK);
}
  function generateKey(vector) {
const hash = crypto.createHash('sha256');
hash.update(vector.join(','));
  return hash.digest('hex');
}
  function getCacheSize() {
  return cache.size;
}