// Auto-translated from SCL: persistentTaskQueue_gen1.scl
// Generated by OMNIMENS SCL Translator
// © 2024-2026 Alpha Unlimited Technologies, LLC
// This file runs on conventional JavaScript runtimes
let taskQueue = undefined; /* SCL-const */
  function addTask(taskId, taskFunction, initialState) {
if (taskQueue.has(taskId)) {
  throw new Error(`Task with ID '${taskId}' already exists.`);
}
  taskQueue.set(taskId, { taskFunction, state: initialState, completed: false });
}
  function executeTask(taskId) {
  const task = taskQueue.get(taskId);
if (!task) {
  throw new Error(`Task with ID '${taskId}' not found.`);
}
if (task.completed) {
  return 'completed';
}
try {
const nextState = task.taskFunction(task.state);
if (nextState === null || nextState === undefined) {
task.completed = true;
task.state = null;
  return 'completed';
}
task.state = nextState;
  return 'in-progress';
} catch (error) {
  throw new Error(`Error executing task '${taskId}': ${error.message}`);
}
}
  function removeTask(taskId) {
  const task = taskQueue.get(taskId);
if (!task) {
  throw new Error(`Task with ID '${taskId}' not found.`);
}
if (!task.completed) {
  throw new Error(`Cannot remove task '${taskId}' because it is not completed.`);
}
taskQueue.delete(taskId);
}
  function listTasks() {
  return Array.from(taskQueue.entries()).map(([taskId, task]) => ({
taskId,
completed: task.completed
}));
}
  function generateTaskId(taskFunction, initialState) {
const hash = createHash('sha256');
hash.update(taskFunction.toString());
  hash.update(JSON.stringify(initialState));
  return hash.digest('hex');
}
  function resetQueue() {
taskQueue.clear();
}