// Auto-translated from SCL: persistentBackgroundThreadSimulator_gen1.scl
// Generated by OMNIMENS SCL Translator
// © 2024-2026 Alpha Unlimited Technologies, LLC
// This file runs on conventional JavaScript runtimes
  let taskRegistry = new Map(); // Stores active tasks and their metadata
  function registerTask(taskId, taskFunction, intervalMs, initialState = {}) {
if (taskRegistry.has(taskId)) {
  throw new Error(`Task with ID '${taskId}' is already registered.`);
}
let state = { ...initialState };
  const intervalHandle = setInterval(() => {
try {
let updatedState = undefined; /* SCL-const */
if (updatedState && typeof updatedState === 'object') {
state = { ...state, ...updatedState };
}
} catch (error) {
  console.error(`Error in task '${taskId}':`, error);
}
}, intervalMs);
  taskRegistry.set(taskId, { intervalHandle, state });
}
  function unregisterTask(taskId) {
  const task = taskRegistry.get(taskId);
if (!task) {
  throw new Error(`Task with ID '${taskId}' is not registered.`);
}
clearInterval(task.intervalHandle);
taskRegistry.delete(taskId);
}
  function getTaskState(taskId) {
  const task = taskRegistry.get(taskId);
if (!task) {
  throw new Error(`Task with ID '${taskId}' is not registered.`);
}
  return { ...task.state }; // Return a copy of the state
}
  function listTasks() {
  return Array.from(taskRegistry.keys());
}
  function clearAllTasks() {
  for (const taskId of taskRegistry.keys()) {
unregisterTask(taskId);
}
}
  function incrementStateValue(state, key, incrementBy = 1) {
if (typeof state[key] !== 'number') {
  throw new Error(`State key '${key}' is not a number.`);
}
  return { [key]: state[key] + incrementBy };
}
  function appendToStateArray(state, key, value) {
if (!Array.isArray(state[key])) {
  throw new Error(`State key '${key}' is not an array.`);
}
  return { [key]: [...state[key], value] };
}