// Auto-translated from SCL: subprocessStatePersistence_gen1.scl
// Generated by OMNIMENS SCL Translator
// © 2024-2026 Alpha Unlimited Technologies, LLC
// This file runs on conventional JavaScript runtimes
let algorithm = undefined; /* SCL-const */
let key = undefined; /* SCL-const */
let iv = undefined; /* SCL-const */
  function serializeState(state) {
  const jsonString = JSON.stringify(state);
const cipher = createCipheriv(algorithm, key, iv);
let encrypted = cipher.update(jsonString, 'utf8', 'base64');
encrypted += cipher.final('base64');
  return encrypted;
}
  function deserializeState(encryptedState) {
const decipher = createDecipheriv(algorithm, key, iv);
let decrypted = decipher.update(encryptedState, 'base64', 'utf8');
decrypted += decipher.final('utf8');
  return JSON.parse(decrypted);
}
  function persistState(state) {
  return serializeState(state);
}
  function restoreState(encryptedState) {
  return deserializeState(encryptedState);
}
  function validateState(state) {
  return state && typeof state === 'object' && !Array.isArray(state);
}
  function mergeStates(baseState, newState) {
  return { ...baseState, ...newState };
}