/**
 * OMNIMENS Self-Authored Module (Migrated from DB)
 * Original Source: agent_mesh_cycle_1
 * Name: dynamicRoleOrchestration
 * Purpose: Generated by agent mesh cycle 1
 * Description: Dynamically reallocates agent roles based on system-wide metrics.
 * Migrated: 2026-03-25T22:49:34.235Z
 */

export function orchestrateRoles(agents, metrics) {
  const roles = agents.map(agent => {
    return {
      agent: agent,
      role: determineOptimalRole(agent, metrics)
    };
  });

  function determineOptimalRole(agent, metrics) {
    const performance = metrics.performance[agent.id];
    const learningRate = metrics.learningRate[agent.id];
    const capabilityGaps = metrics.capabilityGaps[agent.id];

    if (performance < 0.5) {
      return 'support';
    } else if (learningRate > 0.8) {
      return 'leader';
    } else if (capabilityGaps.length > 0) {
      return 'specialist';
    } else {
      return 'generalist';
    }
  }

  return roles;
}
