/**
 * OMNIMENS Self-Authored Module (Migrated from DB)
 * Original Source: agent_mesh_cycle_1
 * Name: entropyConfidenceScorer
 * Purpose: Generated by agent mesh cycle 1
 * Description: Calculates entropy-based confidence scores to quantify uncertainty in reasoning chains.
 * Migrated: 2026-03-25T22:49:34.132Z
 */

export class EntropyConfidenceScorer {
  static calculateEntropy(probabilities) {
    return probabilities.reduce((entropy, prob) => {
      if (prob > 0) {
        entropy -= prob * Math.log2(prob);
      }
      return entropy;
    }, 0);
  }

  static scoreConsistency(reasoningChains) {
    const chainProbabilities = reasoningChains.map(chain => chain.probability);
    const entropy = this.calculateEntropy(chainProbabilities);
    return 1 - entropy / Math.log2(reasoningChains.length);
  }
}