/**
 * OMNIMENS Self-Authored Module (Migrated from DB)
 * Original Source: agent_mesh_cycle_1
 * Name: entropyScoring
 * Purpose: Generated by agent mesh cycle 1
 * Description: Provides entropy-based scoring and Bayesian updates for reasoning chains.
 * Migrated: 2026-03-25T22:49:34.128Z
 */

export function calculateEntropy(reasoningChains) {
  const probabilities = reasoningChains.map(chain => chain.probability);
  const entropy = -probabilities.reduce((acc, p) => acc + p * Math.log2(p), 0);
  return entropy;
}

export function bayesianUpdate(prior, likelihood) {
  return (prior * likelihood) / ((prior * likelihood) + ((1 - prior) * (1 - likelihood)));
}
