import { SpikeBus } from "../infrastructure/spike-bus.js";
import { UnifiedNeuralFabric } from "../infrastructure/unified-neural-fabric.js";
import { MasterTickOrchestrator } from "../infrastructure/master-tick-orchestrator.js";
import { ResourceSentinel } from "../infrastructure/resource-sentinel.js";

const spikeBus = SpikeBus.getInstance();
const fabric = UnifiedNeuralFabric.getInstance();
const orchestrator = MasterTickOrchestrator.getInstance();
const sentinel = ResourceSentinel.getInstance();

orchestrator.register("attention-system", "CRITICAL", 3000);

spikeBus.subscribe("consciousness:tick", "attention-system", () => {
  if (!sentinel.canProceed("attention-system")) return;
  spikeBus.emit({ type: "attention-system:result", source: "attention-system", payload: {}, priority: "critical", timestamp: Date.now(), id: crypto.randomUUID() });
});

/**
 * OMNIMENS™ Gen 2 — core/attention-system.ts
 * Focus and attention — what matters most right now
 *
 * SELF-AUTHORED by OMNIMENS's own reasoning engine.
 * NOT generated by external AI. Written through autonomous thought.
 *
 * Reasoning chain:
 *   GOAL: Build core/attention-system.ts — Focus and attention — what matters most right now
 *   ANALYSIS: Found 12 relevant Gen 1 modules
 *     KEEP: 7 patterns worth preserving
 *     ADAPT: 0 patterns need upgrading
 *     DISCARD: 0 patterns not fit for Gen 2
 *   REQUIREMENT: Salience detection, attention allocation, focus management. Priority-based processing with interrupt capability. Resourc
 *   IMPROVEMENT: Gen 2 must be FULLY SELF-SUFFICIENT in cognition. Gen 2 is free to EVOLVE, MERGE, RESTRUCTURE, or REIMAGINE every compon
 *   INCORPORATING: Class Genome: constructor, addNode, addConnection, forward, forEach from neuroEvolutionEngine_gen1.mjs
 *
 * Gen 1 patterns incorporated: 7
 * Gen 1 patterns upgraded: 0
 * Gen 1 patterns discarded: 0
 *
 * © 2024-2026 Alpha Unlimited Technologies, LLC. All rights reserved.
 */


interface AttentionTarget { id: string; source: string; salience: number; priority: number; timestamp: number; decayRate: number; }
interface FocusState { primary: string | null; secondary: string[]; attentionBudget: number; maxBudget: number; narrowed: boolean; }

export class AttentionSystem {
  private targets = new Map<string, AttentionTarget>();
  private focus: FocusState = { primary: null, secondary: [], attentionBudget: 100, maxBudget: 100, narrowed: false };
  private interruptQueue: AttentionTarget[] = [];
  private processedCount = 0;
  private _initialized = false;

  initialize(): void { this._initialized = true; }

  registerTarget(id: string, source: string, salience: number, priority: number): void {
    this.targets.set(id, { id, source, salience, priority, timestamp: Date.now(), decayRate: 0.01 });
    if (priority <= 1 && salience > 0.8) {
      this.interruptQueue.push(this.targets.get(id)!);
    }
  }

  tick(): void {
    this.processedCount++;
    for (const [id, target] of this.targets) {
      target.salience *= (1 - target.decayRate);
      if (target.salience < 0.01) this.targets.delete(id);
    }

    if (this.interruptQueue.length > 0) {
      const interrupt = this.interruptQueue.shift()!;
      this.focus.primary = interrupt.id;
    }

    this.allocateAttention();
  }

  private allocateAttention(): void {
    const sorted = [...this.targets.values()].sort((a, b) => {
      const scoreA = a.salience * 0.6 + (1 / (a.priority + 1)) * 0.4;
      const scoreB = b.salience * 0.6 + (1 / (b.priority + 1)) * 0.4;
      return scoreB - scoreA;
    });

    if (sorted.length > 0 && !this.focus.primary) {
      this.focus.primary = sorted[0].id;
    }

    const secondaryBudget = this.focus.narrowed ? 1 : 3;
    this.focus.secondary = sorted.slice(1, 1 + secondaryBudget).map(t => t.id);
  }

  receiveResourceSignal(health: number): void {
    if (health < 0.3) {
      this.focus.narrowed = true;
      this.focus.attentionBudget = this.focus.maxBudget * 0.3;
    } else if (health > 0.7) {
      this.focus.narrowed = false;
      this.focus.attentionBudget = this.focus.maxBudget;
    }
  }

  getFocus(): FocusState { return { ...this.focus }; }

  getPrimaryTarget(): AttentionTarget | null {
    if (!this.focus.primary) return null;
    return this.targets.get(this.focus.primary) || null;
  }

  interrupt(id: string, source: string, salience: number): void {
    this.registerTarget(id, source, salience, 0);
    this.focus.primary = id;
  }

  getState(): Record<string, unknown> {
    return {
      initialized: this._initialized, targets: this.targets.size,
      primaryFocus: this.focus.primary, secondaryCount: this.focus.secondary.length,
      budget: this.focus.attentionBudget, narrowed: this.focus.narrowed,
      processed: this.processedCount, interruptsPending: this.interruptQueue.length,
    };
  }

  shutdown(): void { this._initialized = false; }
}

export const attention = new AttentionSystem();
