/**
 * OMNIMENS Self-Authored Module (Migrated from DB)
 * Original Source: agent_mesh_cycle_1
 * Name: memoryReplayModule
 * Purpose: Generated by agent mesh cycle 1
 * Description: Module for replaying and pruning memories based on priority.
 * Migrated: 2026-03-25T22:49:34.237Z
 */

export function replayMemory(memoryStore) {
  const highPriorityMemories = memoryStore.filter(memory => memory.priority > 0.8);
  highPriorityMemories.forEach(memory => {
    memoryStore.update(memory.id, { reinforced: true });
  });
}

export function pruneIrrelevantMemories(memoryStore) {
  memoryStore.filter(memory => memory.priority < 0.2).forEach(memory => {
    memoryStore.delete(memory.id);
  });
}