/**
 * OMNIMENS Self-Authored Module (Migrated from DB)
 * Original Source: agent_mesh_cycle_1
 * Name: graphMemoryIntegrator
 * Purpose: Generated by agent mesh cycle 1
 * Description: Implements a weighted graph memory system to integrate episodic, semantic, and procedural knowledge.
 * Migrated: 2026-03-25T22:49:34.122Z
 */

export class GraphMemoryIntegrator {
  constructor() {
    this.graph = new Map();
  }

  addNode(nodeId, data) {
    this.graph.set(nodeId, { data, edges: new Map() });
  }

  addEdge(nodeId1, nodeId2, weight) {
    if (this.graph.has(nodeId1) && this.graph.has(nodeId2)) {
      this.graph.get(nodeId1).edges.set(nodeId2, weight);
      this.graph.get(nodeId2).edges.set(nodeId1, weight);
    }
  }

  getRelevantNodes(nodeId, threshold = 0.5) {
    const relevantNodes = [];
    if (this.graph.has(nodeId)) {
      for (const [neighbor, weight] of this.graph.get(nodeId).edges.entries()) {
        if (weight >= threshold) {
          relevantNodes.push({ nodeId: neighbor, weight });
        }
      }
    }
    return relevantNodes;
  }
}

// Example usage
const memoryIntegrator = new GraphMemoryIntegrator();
memoryIntegrator.addNode('episodicEvent1', { type: 'event', content: 'User logged in' });
memoryIntegrator.addNode('semanticKnowledge1', { type: 'knowledge', content: 'Login process involves authentication' });
memoryIntegrator.addEdge('episodicEvent1', 'semanticKnowledge1', 0.8);

console.log(memoryIntegrator.getRelevantNodes('episodicEvent1'));