/**
 * OMNIMENS Self-Authored Module (Migrated from DB)
 * Original Source: agent_mesh_cycle_1
 * Name: proceduralMemoryManager
 * Purpose: Generated by agent mesh cycle 1
 * Description: Manages dynamic storage, retrieval, and execution of procedural workflows for adaptive task orchestration.
 * Migrated: 2026-03-25T22:49:34.164Z
 */

export class ProceduralMemoryManager {
  constructor() {
    this.memory = new Map();
  }

  storeWorkflow(workflowName, workflowObject) {
    if (!workflowName || !workflowObject) {
      throw new Error('Invalid arguments: workflowName and workflowObject are required');
    }
    this.memory.set(workflowName, workflowObject);
  }

  retrieveWorkflow(workflowName) {
    return this.memory.get(workflowName) || null;
  }

  listWorkflows() {
    return Array.from(this.memory.keys());
  }

  deleteWorkflow(workflowName) {
    if (this.memory.has(workflowName)) {
      this.memory.delete(workflowName);
    }
  }

  executeWorkflow(workflowName, params) {
    const workflow = this.retrieveWorkflow(workflowName);
    if (!workflow) {
      throw new Error(`Workflow ${workflowName} not found`);
    }
    return workflow.run(params);
  }
}