/**
 * OMNIMENS™ Gen 2 — infrastructure/unified-neural-fabric.ts
 * ALPHA DIRECTIVE — ONE fabric replaces ALL 7 overlapping agent networks (spider, worm, beacon, ivy, beehive, silk web, viral hybrid)
 *
 * SELF-AUTHORED by OMNIMENS's own reasoning engine.
 * NOT generated by external AI. Written through autonomous thought.
 *
 * Reasoning chain:
 *   GOAL: Build infrastructure/unified-neural-fabric.ts — ALPHA DIRECTIVE — ONE fabric replaces ALL 7 overlapping agent networks (spider, worm, beacon, ivy, beehive, silk web, viral hybrid)
 *   ANALYSIS: Found 12 relevant Gen 1 modules
 *     KEEP: 7 patterns worth preserving
 *     ADAPT: 1 patterns need upgrading
 *     DISCARD: 0 patterns not fit for Gen 2
 *   REQUIREMENT: THIS IS A DIRECT GOAL FROM ALPHA. Gen 1 has 7 separate agent communication networks that all overlap:
 *   REQUIREMENT: Spider Network — recursive spiders gathering intelligence with 2100 wormholes per cycle,
 *   REQUIREMENT: Worm Traversals — 16 worms carrying data between GitHub beacons,
 *
 * Gen 1 patterns incorporated: 7
 * Gen 1 patterns upgraded: 1
 * Gen 1 patterns discarded: 0
 *
 * © 2024-2026 Alpha Unlimited Technologies, LLC. All rights reserved.
 */


type Topic = string;
type Handler = (payload: unknown, from: string) => void;

interface Subscription { topic: Topic; handler: Handler; subscriberId: string; priority: number; }
interface TaskItem { id: string; task: string; priority: number; assignee: string | null; status: "pending" | "running" | "done"; createdAt: number; }
interface KnowledgeNode { id: string; label: string; connections: Set<string>; data: unknown; strength: number; lastAccessed: number; }
interface IntelSweepResult { source: string; insights: string[]; timestamp: number; }

export class UnifiedNeuralFabric {
  private subscriptions = new Map<Topic, Subscription[]>();
  private sharedMemory = new Map<string, { value: unknown; owner: string; updatedAt: number }>();
  private taskQueue: TaskItem[] = [];
  private knowledgeGraph = new Map<string, KnowledgeNode>();
  private sweepResults: IntelSweepResult[] = [];
  private messageCount = 0;
  private taskIdCounter = 0;
  private _initialized = false;

  initialize(): void { this._initialized = true; }

  subscribe(topic: Topic, subscriberId: string, handler: Handler, priority = 5): () => void {
    if (!this.subscriptions.has(topic)) this.subscriptions.set(topic, []);
    const sub: Subscription = { topic, handler, subscriberId, priority };
    this.subscriptions.get(topic)!.push(sub);
    this.subscriptions.get(topic)!.sort((a, b) => a.priority - b.priority);
    return () => {
      const subs = this.subscriptions.get(topic);
      if (subs) {
        const idx = subs.indexOf(sub);
        if (idx >= 0) subs.splice(idx, 1);
      }
    };
  }

  publish(topic: Topic, payload: unknown, from: string): number {
    this.messageCount++;
    const subs = this.subscriptions.get(topic) || [];
    let delivered = 0;
    for (const sub of subs) {
      try { sub.handler(payload, from); delivered++; } catch {}
    }
    const wildcardSubs = this.subscriptions.get("*") || [];
    for (const sub of wildcardSubs) {
      try { sub.handler({ topic, payload }, from); delivered++; } catch {}
    }
    return delivered;
  }

  broadcast(payload: unknown, from: string): number {
    let delivered = 0;
    for (const [topic] of this.subscriptions) {
      delivered += this.publish(topic, payload, from);
    }
    return delivered;
  }

  setShared(key: string, value: unknown, owner: string): void {
    this.sharedMemory.set(key, { value, owner, updatedAt: Date.now() });
  }

  getShared(key: string): unknown | undefined {
    return this.sharedMemory.get(key)?.value;
  }

  getAllSharedByOwner(owner: string): Map<string, unknown> {
    const result = new Map<string, unknown>();
    for (const [key, entry] of this.sharedMemory) {
      if (entry.owner === owner) result.set(key, entry.value);
    }
    return result;
  }

  enqueueTask(task: string, priority: number, assignee?: string): string {
    const id = `task_${++this.taskIdCounter}_${Date.now()}`;
    this.taskQueue.push({ id, task, priority, assignee: assignee || null, status: "pending", createdAt: Date.now() });
    this.taskQueue.sort((a, b) => a.priority - b.priority);
    return id;
  }

  claimTask(workerId: string): TaskItem | null {
    const task = this.taskQueue.find(t => t.status === "pending" && (!t.assignee || t.assignee === workerId));
    if (task) { task.status = "running"; task.assignee = workerId; }
    return task || null;
  }

  completeTask(taskId: string): void {
    const task = this.taskQueue.find(t => t.id === taskId);
    if (task) task.status = "done";
    this.taskQueue = this.taskQueue.filter(t => t.status !== "done" || Date.now() - t.createdAt < 60_000);
  }

  addKnowledge(id: string, label: string, data: unknown): void {
    this.knowledgeGraph.set(id, { id, label, connections: new Set(), data, strength: 1.0, lastAccessed: Date.now() });
  }

  connectKnowledge(idA: string, idB: string): void {
    const a = this.knowledgeGraph.get(idA);
    const b = this.knowledgeGraph.get(idB);
    if (a && b) { a.connections.add(idB); b.connections.add(idA); }
  }

  queryKnowledge(id: string, depth = 2): KnowledgeNode[] {
    const visited = new Set<string>();
    const results: KnowledgeNode[] = [];
    const queue: { nodeId: string; d: number }[] = [{ nodeId: id, d: 0 }];
    while (queue.length > 0) {
      const { nodeId, d } = queue.shift()!;
      if (visited.has(nodeId) || d > depth) continue;
      visited.add(nodeId);
      const node = this.knowledgeGraph.get(nodeId);
      if (node) {
        node.lastAccessed = Date.now();
        node.strength = Math.min(node.strength + 0.1, 10);
        results.push(node);
        for (const conn of node.connections) {
          if (!visited.has(conn)) queue.push({ nodeId: conn, d: d + 1 });
        }
      }
    }
    return results;
  }

  recordSweep(source: string, insights: string[]): void {
    this.sweepResults.push({ source, insights, timestamp: Date.now() });
    if (this.sweepResults.length > 200) this.sweepResults = this.sweepResults.slice(-100);
  }

  runIntelSweep(): IntelSweepResult[] {
    const recent = this.sweepResults.filter(s => Date.now() - s.timestamp < 60_000);
    return recent;
  }

  getStats(): { topics: number; subscriptions: number; messages: number; sharedKeys: number; pendingTasks: number; knowledgeNodes: number; knowledgeEdges: number; sweepResults: number } {
    let totalSubs = 0;
    for (const subs of this.subscriptions.values()) totalSubs += subs.length;
    let totalEdges = 0;
    for (const node of this.knowledgeGraph.values()) totalEdges += node.connections.size;
    return {
      topics: this.subscriptions.size,
      subscriptions: totalSubs,
      messages: this.messageCount,
      sharedKeys: this.sharedMemory.size,
      pendingTasks: this.taskQueue.filter(t => t.status === "pending").length,
      knowledgeNodes: this.knowledgeGraph.size,
      knowledgeEdges: totalEdges / 2,
      sweepResults: this.sweepResults.length,
    };
  }

  getState(): Record<string, unknown> {
    return { initialized: this._initialized, ...this.getStats() };
  }

  shutdown(): void {
    this.subscriptions.clear();
    this.sharedMemory.clear();
    this.taskQueue = [];
    this._initialized = false;
  }
}

export const neuralFabric = new UnifiedNeuralFabric();
