/**
 * OMNIMENS Self-Authored Module (Migrated from DB)
 * Original Source: agent_mesh_cycle_1
 * Name: eventDrivenTaskAllocator
 * Purpose: Generated by agent mesh cycle 1
 * Description: Implements a pub/sub system for dynamic task delegation across agents.
 * Migrated: 2026-03-25T22:49:34.132Z
 */

export class EventDrivenTaskAllocator {
  constructor() {
    this.subscribers = {};
  }

  subscribe(eventType, agent) {
    if (!this.subscribers[eventType]) {
      this.subscribers[eventType] = [];
    }
    this.subscribers[eventType].push(agent);
  }

  publish(eventType, task) {
    const agents = this.subscribers[eventType] || [];
    agents.forEach(agent => agent.handleTask(task));
  }

  escalate(eventType, task, threshold) {
    const agents = this.subscribers[eventType] || [];
    agents.forEach(agent => {
      if (agent.getLoad() < threshold) {
        agent.handleTask(task);
      } else {
        console.warn(`Agent ${agent.name} unable to handle task due to load.`);
      }
    });
  }
}