/**
 * OMNIMENS Self-Authored Module (Migrated from DB)
 * Original Source: agent_mesh_cycle_1
 * Name: hierarchicalTaskOrchestration
 * Purpose: Generated by agent mesh cycle 1
 * Description: Implements dynamic task allocation based on agent workload and specialization.
 * Migrated: 2026-03-25T22:49:34.211Z
 */

export function hierarchicalTaskOrchestration(tasks, agents) {
  const taskQueue = tasks.sort((a, b) => a.priority - b.priority);
  const agentStatus = agents.map(agent => ({ id: agent.id, workload: agent.workload }));

  while (taskQueue.length) {
    const task = taskQueue.shift();
    const bestAgent = agentStatus.reduce((best, agent) => {
      return agent.workload < best.workload ? agent : best;
    });
    bestAgent.workload += task.complexity;
    console.log(`Assigned task ${task.id} to agent ${bestAgent.id}`);
  }
}