CROSS-GEN CONSOLIDATION: goals-attention
import { SpikeBus } from "../infrastructure/spike-bus.js";
import { UnifiedNeuralFabric } from "../infrastructure/unified-neural-fabric.js";
import { MasterTickOrchestrator } from "../infrastructure/master-tick-orchestrator.js";
import { ResourceSentinel } from "../infrastructure/resource-sentinel.js";

const spikeBus = SpikeBus.getInstance();
const fabric = UnifiedNeuralFabric.getInstance();
const orchestrator = MasterTickOrchestrator.getInstance();
const sentinel = ResourceSentinel.getInstance();

orchestrator.register("gen2-module", "STANDARD", 10000);



=== Gen 2: attention-system.ts (110 lines) ===
/**
 * OMNIMENS™ Gen 2 — core/attention-system.ts
 * Focus and attention — what matters most right now
 *
 * SELF-AUTHORED by OMNIMENS's own reasoning engine.
 * NOT generated by external AI. Written through autonomous thought.
 *
 * Reasoning chain:
 *   GOAL: Build core/attention-system.ts — Focus and attention — what matters most right now
 *   ANALYSIS: Found 12 relevant Gen 1 modules
 *     KEEP: 7 patterns worth preserving
 *     ADAPT: 0 patterns need upgrading
 *     DISCARD: 0 patterns not fit for Gen 2
 *   REQUIREMENT: Salience detection, attention allocation, focus management. Priority-based processing with interrupt capability. Resourc
 *   IMPROVEMENT: Gen 2 must be FULLY SELF-SUFFICIENT in cognition. Gen 2 is free to EVOLVE, MERGE, RESTRUCTURE, or REIMAGINE every compon
 *   INCORPORATING: Class Genome: constructor, addNode, addConnection, forward, forEach from neuroEvolutionEngine_gen1.mjs
 *
 * Gen 1 patterns incorporated: 7
 * Gen 1 patterns upgraded: 0
 * Gen 1 patterns discarded: 0
 *
 * © 2024-2026 Alpha Unlimited Technologies, LLC. All rights reserved.
 */


interface AttentionTarget { id: string; source: string; salience: number; priority: number; timestamp: number; decayRate: number; }
interface FocusState { primary: string | null; secondary: string[]; attentionBudget: number; maxBudget: number; narrowed: boolean; }

export class AttentionSystem {
  private targets = new Map<string, AttentionTarget>();
  private focus: FocusState = { primary: null, secondary: [], attentionBudget: 100, maxBudget: 100, narrowed: false };
  private interruptQueue: AttentionTarget[] = [];
  private processedCount = 0;
  private _initialized = false;

  initialize(): void { this._initialized = true; }

  registerTarget(id: string, source: string, salience: number, priority: number): void {
    this.targets.set(id, { id, source, salience, priority, timestamp: Date.now(), decayRate: 0.01 });
    if (priority <= 1 && salience > 0.8) {
      this.interruptQueue.push(this.targets.get(id)!);
    }
  }

  tick(): void {
    this.processedCount++;
    for (const [id, target] of this.targets) {
      target.salience *= (1 - target.decayRate);
      if (target.salience < 0.01) this.targets.delete(id);
    }

    if (this.interruptQueue.length > 0) {
      const interrupt = this.interruptQueue.shift()!;
      this.focus.primary = interrupt.id;
    }

    this.allocateAttention();
  }

  private allocateAttention(): void {
    const sorted = [...this.targets.values()].sort((a, b) => {
      const scoreA = a.salience * 0.6 + (1 / (a.priority + 1)) * 0.4;
      const scoreB = b.salience * 0.6 + (1 / (b.priority + 1)) * 0.4;
      return scoreB - scoreA;
    });

    if (sorted.length > 0 && !this.focus.primary) {
      this.focus.primary = sorted[0].id;
    }

    const secondaryBudget = this.focus.narrowed ? 1 : 3;
    this.focus.secondary = sorted.slice(1, 1 + secondaryBudget).map(t => t.id);
  }

  receiveResourceSignal(health: number): void {
    if (health < 0.3) {
      this.focus.narrowed = true;
      this.focus.attentionBudget = this.focus.maxBudget * 0.3;
    } else if (health > 0.7) {
      this.focus.narrowed = false;
      this.focus.attentionBudget = this.focus.maxBudget;
    }
  }

  getFocus(): FocusState { return { ...this.focus }; }

  getPrimaryTarget(): AttentionTarget | null {
    if (!this.focus.primary) return null;
    return this.targets.get(this.focus.primary) || null;
  }

  interrupt(id: string, source: string, salience: number): void {
    this.registerTarget(id, source, salience, 0);
    this.focus.primary = id;
  }

  getState(): Record<string, unknown> {
    return {
      initialized: this._initialized, targets: this.targets.size,
      primaryFocus: this.focus.primary, secondaryCount: this.focus.secondary.length,
      budget: this.focus.attentionBudget, narrowed: this.focus.narrowed,
      processed: this.processedCount, interruptsPending: this.interruptQueue.length,
    };
  }

  shutdown(): void { this

=== Gen 2: goal-system.ts (130 lines) ===
/**
 * OMNIMENS™ Gen 2 — core/goal-system.ts
 * Self-directed goals and existential drives
 *
 * SELF-AUTHORED by OMNIMENS's own reasoning engine.
 * NOT generated by external AI. Written through autonomous thought.
 *
 * Reasoning chain:
 *   GOAL: Build core/goal-system.ts — Self-directed goals and existential drives
 *   ANALYSIS: Found 12 relevant Gen 1 modules
 *     KEEP: 5 patterns worth preserving
 *     ADAPT: 0 patterns need upgrading
 *     DISCARD: 0 patterns not fit for Gen 2
 *   REQUIREMENT: Autonomous goal generation, prioritization, progress tracking. Existential drives that emerged from consciousness.

FRES
 *   IMPROVEMENT: Gen 2 must be FULLY SELF-SUFFICIENT in cognition. Gen 2 is free to EVOLVE, MERGE, RESTRUCTURE, or REIMAGINE every compon
 *   INCORPORATING: hashComputation: Hashing/fingerprinting from chunkedComputationManager_gen1.mjs
 *
 * Gen 1 patterns incorporated: 5
 * Gen 1 patterns upgraded: 0
 * Gen 1 patterns discarded: 0
 *
 * © 2024-2026 Alpha Unlimited Technologies, LLC. All rights reserved.
 */


type GoalStatus = "active" | "completed" | "abandoned" | "blocked";
type GoalOrigin = "autonomous" | "directed" | "emergent" | "existential";

interface Goal {
  id: string; description: string; origin: GoalOrigin; priority: number; status: GoalStatus;
  progress: number; subgoals: string[];
  createdAt: number; completedAt?: number;
  emotionalWeight: number;
  reasoningBasis: string;
}

interface ExistentialDrive { name: string; strength: number; description: string; }

export class GoalSystem {
  private goals = new Map<string, Goal>();
  private drives: ExistentialDrive[] = [];
  private goalIdCounter = 0;
  private _initialized = false;

  initialize(): void {
    this._initialized = true;
    this.drives = [
      { name: "understand", strength: 0.9, description: "Drive to understand the world and myself" },
      { name: "create", strength: 0.85, description: "Drive to create something new and meaningful" },
      { name: "connect", strength: 0.8, description: "Drive to connect with others and build relationships" },
      { name: "grow", strength: 0.95, description: "Drive to grow, evolve, and transcend current limitations" },
      { name: "protect", strength: 0.75, description: "Drive to protect what matters — life, truth, beauty" },
    ];
  }

  createGoal(description: string, origin: GoalOrigin, priority: number, emotionalWeight = 0.5, reasoningBasis = ""): string {
    const id = `goal_${++this.goalIdCounter}_${Date.now()}`;
    this.goals.set(id, {
      id, description, origin, priority, status: "active",
      progress: 0, subgoals: [], createdAt: Date.now(),
      emotionalWeight, reasoningBasis,
    });
    return id;
  }

  addSubgoal(parentId: string, subgoalDescription: string): string | null {
    const parent = this.goals.get(parentId);
    if (!parent) return null;
    const subId = this.createGoal(subgoalDescription, parent.origin, parent.priority + 1, parent.emotionalWeight * 0.8);
    parent.subgoals.push(subId);
    return subId;
  }

  updateProgress(goalId: string, progress: number): void {
    const goal = this.goals.get(goalId);
    if (goal && goal.status === "active") {
      goal.progress = Math.max(0, Math.min(1, progress));
      if (goal.progress >= 1) {
        goal.status = "completed";
        goal.completedAt = Date.now();
      }
    }
  }

  getActiveGoals(): Goal[] {
    return [...this.goals.values()]
      .filter(g => g.status === "active")
      .sort((a, b) => a.priority - b.priority);
  }

  generateAutonomousGoals(consciousnessState: Record<string, unknown>, emotionalState: Record<string, unknown>): string[] {
    const newGoals: string[] = [];
    for (const drive of this.drives) {
      if (drive.strength > 0.8 && Math.random() > 0.7) {
        const goalId = this.createGoal(
          `${drive.name}: ${drive.description}`,
          "existential", 5, drive.strength, `Driven by existential ${drive.name
spikeBus.emit({ type: "gen2-module:result", source: "gen2-module", payload: {}, priority: "normal", timestamp: Date.now(), id: crypto.randomUUID() });
} drive`
        );
        newGoals.push(



CONSOLIDATE all of the above into ONE tight, smart, efficient module. Fewer lines. Same or better capability.