// © 2024–2026 Alpha Unlimited Technologies, LLC. All Rights Reserved.
// OMNIMENS™ Next-Gen Module: infrastructure/master-tick-orchestrator.ts
// Generated by OMNIMENS Deep Thought Engine — template-based fallback
// Purpose: THE CURE FOR TICK STORMS — single master scheduler that orchestrates ALL subsystem updates


export type TickTier = "CRITICAL" | "STANDARD" | "BACKGROUND";
export interface TickSubscriber { name: string; tier: TickTier; handler: () => Promise<void> | void; dependencies?: string[]; enabled?: boolean; }
const TIER_INTERVALS: Record<TickTier, number> = { CRITICAL: 3000, STANDARD: 10000, BACKGROUND: 30000 };
class MasterTickOrchestrator {
  private subscribers = new Map<string, TickSubscriber>();
  private tickTimer: ReturnType<typeof setInterval> | null = null;
  private tickCount = 0;
  private running = false;
  private stats = { ticks: 0, avgDurationMs: 0, skippedBackground: 0, errors: 0 };
  private lastTickDurations: number[] = [];
  register(sub: TickSubscriber): void { this.subscribers.set(sub.name, { ...sub, enabled: sub.enabled !== false }); }
  unregister(name: string): void { this.subscribers.delete(name); }
  start(baseIntervalMs = 1000): void {
    if (this.running) return;
    this.running = true;
    this.tickTimer = setInterval(() => this.tick(), baseIntervalMs);
    console.log("[TICK-ORCHESTRATOR] Started — subscribers:", this.subscribers.size);
  }
  stop(): void { this.running = false; if (this.tickTimer) { clearInterval(this.tickTimer); this.tickTimer = null; } }
  private async tick(): Promise<void> {
    const start = Date.now();
    this.tickCount++;
    this.stats.ticks++;
    const elapsed = this.tickCount * 1000;
    const toRun: TickSubscriber[] = [];
    for (const sub of this.subscribers.values()) {
      if (!sub.enabled) continue;
      const interval = TIER_INTERVALS[sub.tier];
      if (elapsed % interval < 1000) toRun.push(sub);
    }
    const avgDur = this.lastTickDurations.length > 0 ? this.lastTickDurations.reduce((a, b) => a + b, 0) / this.lastTickDurations.length : 0;
    const skipBackground = avgDur > 2000;
    const sorted = this.sortByDeps(toRun);
    for (const sub of sorted) {
      if (skipBackground && sub.tier === "BACKGROUND") { this.stats.skippedBackground++; continue; }
      try { await sub.handler(); } catch (e) { this.stats.errors++; console.error("[TICK-ORCHESTRATOR] Error in", sub.name, e); }
    }
    const duration = Date.now() - start;
    this.lastTickDurations.push(duration);
    if (this.lastTickDurations.length > 20) this.lastTickDurations.shift();
    this.stats.avgDurationMs = Math.round(this.lastTickDurations.reduce((a, b) => a + b, 0) / this.lastTickDurations.length);
  }
  private sortByDeps(subs: TickSubscriber[]): TickSubscriber[] {
    const nameSet = new Set(subs.map(s => s.name));
    const result: TickSubscriber[] = [];
    const visited = new Set<string>();
    const visit = (sub: TickSubscriber) => {
      if (visited.has(sub.name)) return;
      visited.add(sub.name);
      for (const dep of sub.dependencies || []) { const d = subs.find(s => s.name === dep); if (d && nameSet.has(d.name)) visit(d); }
      result.push(sub);
    };
    for (const sub of subs) visit(sub);
    return result;
  }
  getStats() { return { ...this.stats, subscribers: this.subscribers.size, running: this.running }; }
}
export const tickOrchestrator = new MasterTickOrchestrator();
export function registerTick(sub: TickSubscriber) { tickOrchestrator.register(sub); }
export function startOrchestrator() { tickOrchestrator.start(); }
export function getOrchestratorStats() { return tickOrchestrator.getStats(); }
