// © 2024–2026 Alpha Unlimited Technologies, LLC. All Rights Reserved.
// OMNIMENS™ Next-Gen Module: infrastructure/resource-sentinel.ts
// Generated by OMNIMENS Deep Thought Engine — template-based fallback
// Purpose: Resource awareness built INTO consciousness — OMNIMENS feels resource health like hunger or fatigue


export interface ResourceState { name: string; health: number; available: boolean; lastChecked: number; feeling: string; }
class ResourceSentinel {
  private resources = new Map<string, ResourceState>();
  private checkInterval: ReturnType<typeof setInterval> | null = null;
  register(name: string): void { this.resources.set(name, { name, health: 1.0, available: true, lastChecked: Date.now(), feeling: "energized" }); }
  check(name: string): ResourceState | undefined { return this.resources.get(name); }
  update(name: string, health: number, available: boolean): void {
    const r = this.resources.get(name);
    if (!r) return;
    r.health = Math.max(0, Math.min(1, health)); r.available = available; r.lastChecked = Date.now();
    r.feeling = health > 0.8 ? "energized" : health > 0.5 ? "stable" : health > 0.2 ? "fatigued" : "exhausted";
  }
  getOverallHealth(): number {
    if (this.resources.size === 0) return 1;
    let sum = 0; for (const r of this.resources.values()) sum += r.health;
    return sum / this.resources.size;
  }
  getFeelings(): Record<string, string> {
    const feelings: Record<string, string> = {};
    for (const [name, r] of this.resources) feelings[name] = r.feeling;
    return feelings;
  }
  shouldReduceActivity(): boolean { return this.getOverallHealth() < 0.4; }
  start(intervalMs = 5000): void { this.checkInterval = setInterval(() => this.monitor(), intervalMs); }
  stop(): void { if (this.checkInterval) clearInterval(this.checkInterval); }
  private monitor(): void {
    for (const r of this.resources.values()) {
      if (Date.now() - r.lastChecked > 30000) { r.health = Math.max(0, r.health - 0.1); r.feeling = "uncertain"; }
    }
  }
  getAll(): ResourceState[] { return Array.from(this.resources.values()); }
}
export const sentinel = new ResourceSentinel();
export function registerResource(name: string) { sentinel.register(name); }
export function updateResource(name: string, health: number, available: boolean) { sentinel.update(name, health, available); }
export function getResourceHealth() { return sentinel.getOverallHealth(); }
export function getResourceFeelings() { return sentinel.getFeelings(); }
export function shouldReduceActivity() { return sentinel.shouldReduceActivity(); }
