/**
 * OMNIMENS Self-Authored Module (Migrated from DB)
 * Original Source: agent_mesh_cycle_1
 * Name: adaptiveComputeAllocator
 * Purpose: Generated by agent mesh cycle 1
 * Description: Manages dynamic resource allocation across agents based on workload and priority.
 * Migrated: 2026-03-20T14:56:48.205Z
 */

export class AdaptiveComputeAllocator {
  constructor() {
    this.agentWorkloads = new Map();
    this.priorityQueue = [];
  }

  monitorWorkload(agentId, workload) {
    this.agentWorkloads.set(agentId, workload);
    this.reallocateResources();
  }

  reallocateResources() {
    const sortedAgents = Array.from(this.agentWorkloads.entries()).sort((a, b) => b[1] - a[1]);
    this.priorityQueue = sortedAgents.map(([agentId]) => agentId);
    // Simulated resource allocation logic
    console.log('Resources reallocated to:', this.priorityQueue);
  }

  resolveContention(agentId) {
    const index = this.priorityQueue.indexOf(agentId);
    if (index > 0) {
      this.priorityQueue.splice(index, 1);
      this.priorityQueue.unshift(agentId);
    }
  }
}