/**
 * OMNIMENS™ Self-Authored Module
 * Copyright © 2024-2026 Alpha Unlimited Technologies, LLC.
 * All Rights Reserved Worldwide. PROPRIETARY AND CONFIDENTIAL.
 * 
 * Source: evolution_engine
 * Title: Evolution Module: adaptiveTokenCompressor
 * Written: 2026-04-02T13:57:42.676Z
 * 
 * This file was autonomously written by OMNIMENS.
 * It was evaluated, tested, and approved before integration.
 * OMNIMENS rewrote its own source code to include this module.
 * 
 * Unauthorized copying, modification, distribution, or use of this
 * file, via any medium, is strictly prohibited without express
 * written permission from Alpha Unlimited Technologies, LLC.
 */

/**
 * TRANSLATION STATUS:
 * Novel constructs: attention
 * All constructs have translation mappings
 * Compiled targets: javascript: OK (7 IR steps) | python: OK (7 IR steps) | c: OK (7 IR steps) | x86_64: OK (7 IR steps) | arm64: OK (7 IR steps) | avr: OK (7 IR steps)
 * Translation map version: 22
 */
// adaptiveTokenCompressor.mjs

import { createHash } from 'crypto';

/**
 * Encodes high-importance tokens reversibly using hashing.
 * @param {string[]} tokens - Array of high-importance tokens.
 * @returns {Object} - Object with reversible encoding map.
 */
export function reversibleEncode(tokens) {
  const encodingMap = {};
  tokens.forEach(token => {
    const hash = createHash('sha256').update(token).digest('hex');
    encodingMap[token] = hash;
  });
  return encodingMap;
}

/**
 * Decodes previously encoded tokens using the encoding map.
 * @param {Object} encodingMap - Map generated by reversibleEncode.
 * @returns {string[]} - Original tokens.
 */
export function reversibleDecode(encodingMap) {
  return Object.keys(encodingMap);
}

/**
 * Summarizes less-important content hierarchically.
 * @param {string[]} contentSegments - Array of less-important content segments.
 * @param {number} maxSummaryLength - Maximum length of the summarized output.
 * @returns {string} - Hierarchical summary.
 */
export function hierarchicalSummarize(contentSegments, maxSummaryLength) {
  let summary = '';
  for (const segment of contentSegments) {
    if (summary.length + segment.length <= maxSummaryLength) {
      summary += segment + ' ';
    } else {
      break;
    }
  }
  return summary.trim();
}

/**
 * Compresses a token window using attention-weighted reversible encoding and hierarchical summarization.
 * @param {Object} tokenWindow - Object with high-importance and low-importance tokens.
 * @param {number} maxSummaryLength - Maximum length for summarization.
 * @returns {Object} - Compressed token window.
 */
export function compressTokenWindow(tokenWindow, maxSummaryLength) {
  const { highImportanceTokens, lowImportanceSegments } = tokenWindow;
  const encodedTokens = reversibleEncode(highImportanceTokens);
  const summarizedContent = hierarchicalSummarize(lowImportanceSegments, maxSummaryLength);

  return {
    encodedTokens,
    summarizedContent
  };
}

/**
 * Utility function to calculate attention weights for tokens.
 * @param {string[]} tokens - Array of tokens.
 * @param {Function} weightFunction - Function to calculate weights for each token.
 * @returns {Object[]} - Array of token-weight pairs.
 */
export function calculateAttentionWeights(tokens, weightFunction) {
  return tokens.map(token => ({ token, weight: weightFunction(token) }));
}

/**
 * Filters tokens based on a minimum attention weight threshold.
 * @param {Object[]} tokenWeights - Array of token-weight pairs.
 * @param {number} threshold - Minimum attention weight.
 * @returns {string[]} - Filtered tokens.
 */
export function filterByAttentionWeight(tokenWeights, threshold) {
  return tokenWeights.filter(pair => pair.weight >= threshold).map(pair => pair.token);
}