/**
 * OMNIMENS Self-Authored Module (Migrated from DB)
 * Original Source: agent_mesh_cycle_1
 * Name: bayesianEvaluator
 * Purpose: Generated by agent mesh cycle 1
 * Description: Implements a Bayesian evaluator for recursive reasoning chain confidence scoring.
 * Migrated: 2026-03-20T14:56:48.207Z
 */

export class BayesianEvaluator {
  constructor() {
    this.entropyThreshold = 0.05;
  }

  calculateEntropy(probabilities) {
    return probabilities.reduce((entropy, prob) => {
      return entropy - (prob > 0 ? prob * Math.log2(prob) : 0);
    }, 0);
  }

  evaluateReasoningChain(reasoningChain) {
    const probabilities = reasoningChain.map(step => step.confidence);
    const entropy = this.calculateEntropy(probabilities);

    if (entropy < this.entropyThreshold) {
      return {
        isConsistent: true,
        entropy
      };
    } else {
      return {
        isConsistent: false,
        entropy
      };
    }
  }
}