/**
 * OMNIMENS Self-Authored Module (Migrated from DB)
 * Original Source: agent_mesh_cycle_1
 * Name: bayesianUncertaintyScoring
 * Purpose: Generated by agent mesh cycle 1
 * Description: Calculates entropy-based self-consistency and Bayesian uncertainty scores for confidence calibration.
 * Migrated: 2026-03-22T03:46:25.883Z
 */

export function calculateUncertaintyScore(inputs, model) {
  const entropy = calculateEntropy(inputs, model);
  const bayesianScore = calculateBayesianUncertainty(inputs, model);
  return {
    entropy,
    bayesianScore,
    combinedScore: (entropy + bayesianScore) / 2
  };
}

function calculateEntropy(inputs, model) {
  const predictions = model.predict(inputs);
  const logProbabilities = predictions.map(p => Math.log(p));
  return -logProbabilities.reduce((sum, logP) => sum + logP, 0);
}

function calculateBayesianUncertainty(inputs, model) {
  const posterior = model.calculatePosterior(inputs);
  return posterior.variance;
}