/**
 * OMNIMENS Self-Authored Module (Migrated from DB)
 * Original Source: agent_mesh_cycle_1
 * Name: bayesianConfidenceCalibration
 * Purpose: Generated by agent mesh cycle 1
 * Description: Provides a function to calculate and update agent confidence based on Bayesian principles.
 * Migrated: 2026-03-22T05:34:48.403Z
 */

export function calculateConfidence(entropy, mutualInfo, historicalAccuracy) {
  const baseConfidence = 1 - entropy;
  const adjustedConfidence = baseConfidence * (1 + mutualInfo) * historicalAccuracy;
  return Math.min(Math.max(adjustedConfidence, 0), 1);
}

export function updateAgentConfidence(agent, entropy, mutualInfo, historicalAccuracy) {
  const confidence = calculateConfidence(entropy, mutualInfo, historicalAccuracy);
  agent.confidenceScore = confidence;
  return agent;
}