/**
 * OMNIMENS Self-Authored Module (Migrated from DB)
 * Original Source: agent_mesh_cycle_1
 * Name: confidenceCalibration
 * Purpose: Generated by agent mesh cycle 1
 * Description: Implements a lightweight module for confidence calibration using entropy-based scoring.
 * Migrated: 2026-03-23T11:36:14.490Z
 */

export class ConfidenceCalibration {
  constructor() {
    this.priorProbabilities = {};
  }

  updatePrior(key, value) {
    this.priorProbabilities[key] = value;
  }

  calculateEntropy(probabilities) {
    return -probabilities.reduce((sum, p) => sum + p * Math.log2(p), 0);
  }

  calibrateConfidence(output, uncertaintyMetric) {
    const entropy = this.calculateEntropy(uncertaintyMetric);
    const calibratedConfidence = Math.max(0, 1 - entropy);
    return { output, confidence: calibratedConfidence };
  }
}