/**
 * OMNIMENS Self-Authored Module (Migrated from DB)
 * Original Source: agent_mesh_cycle_1
 * Name: dynamicKnowledgeGraph
 * Purpose: Generated by agent mesh cycle 1
 * Description: Implements a dynamic knowledge graph to unify inter-agent outputs through conflict resolution.
 * Migrated: 2026-03-20T14:56:48.210Z
 */

export class DynamicKnowledgeGraph {
  constructor() {
    this.graph = new Map();
  }

  addNode(agentId, data) {
    if (!this.graph.has(agentId)) {
      this.graph.set(agentId, { data: data, edges: [] });
    }
  }

  addEdge(sourceAgent, targetAgent, weight) {
    if (this.graph.has(sourceAgent) && this.graph.has(targetAgent)) {
      this.graph.get(sourceAgent).edges.push({ target: targetAgent, weight: weight });
    }
  }

  resolveConflicts() {
    const results = {};

    for (const [agentId, node] of this.graph.entries()) {
      const weightedSum = node.edges.reduce((sum, edge) => sum + edge.weight, 0);
      results[agentId] = { data: node.data, weightedConfidence: weightedSum / node.edges.length };
    }

    return Object.entries(results).sort((a, b) => b[1].weightedConfidence - a[1].weightedConfidence);
  }
}

// Usage example:
const graph = new DynamicKnowledgeGraph();
graph.addNode('AgentA', { output: 'Value1' });
graph.addNode('AgentB', { output: 'Value2' });
graph.addEdge('AgentA', 'AgentB', 0.8);
graph.addEdge('AgentB', 'AgentA', 0.6);
console.log(graph.resolveConflicts());