/**
 * OMNIMENS Self-Authored Module (Migrated from DB)
 * Original Source: agent_mesh_cycle_1
 * Name: dynamicCISCThresholding
 * Purpose: Generated by agent mesh cycle 1
 * Description: Implements dynamic thresholding for CISC based on adversarial interaction history.
 * Migrated: 2026-03-22T14:41:22.468Z
 */

export class DynamicCISCThresholding {
  constructor() {
    this.adversarialLog = [];
    this.baseThreshold = 0.8;
  }

  logInteraction(interaction) {
    this.adversarialLog.push(interaction);
    if (this.adversarialLog.length > 100) {
      this.adversarialLog.shift(); // Maintain lightweight log
    }
  }

  calculateThreshold() {
    const recentInteractions = this.adversarialLog.slice(-20);
    const adversarialCount = recentInteractions.filter(i => i.isAdversarial).length;
    return Math.min(1, this.baseThreshold + adversarialCount * 0.01);
  }
}