/**
 * OMNIMENS Self-Authored Module (Migrated from DB)
 * Original Source: agent_mesh_cycle_1
 * Name: dynamicRoleAllocator
 * Purpose: Generated by agent mesh cycle 1
 * Description: Implements dynamic role allocation for agents based on performance metrics.
 * Migrated: 2026-03-20T14:56:48.208Z
 */

export class DynamicRoleAllocator {
  constructor() {
    this.agents = [];
  }

  registerAgent(agent) {
    this.agents.push(agent);
  }

  allocateRoles(metrics) {
    this.agents.sort((a, b) => metrics[b.id] - metrics[a.id]);
    this.agents.forEach((agent, index) => {
      agent.role = index === 0 ? 'primary' : 'secondary';
    });
  }
}