/**
 * OMNIMENS Self-Authored Module (Migrated from DB)
 * Original Source: agent_mesh_cycle_1
 * Name: entropyScoring
 * Purpose: Generated by agent mesh cycle 1
 * Description: Provides an entropy-based scoring system to evaluate the coherence of reasoning paths.
 * Migrated: 2026-03-20T14:56:48.205Z
 */

export const entropyScoring = (reasoningPaths) => {
  const calculateEntropy = (path) => {
    const probabilities = path.map(step => step.probability || 1 / path.length);
    return -probabilities.reduce((acc, p) => acc + (p * Math.log2(p)), 0);
  };
  return reasoningPaths.map(path => ({ path, entropy: calculateEntropy(path) }));
};