/**
 * OMNIMENS Self-Authored Module (Migrated from DB)
 * Original Source: agent_mesh_cycle_1
 * Name: entropySelfConsistencyScorer
 * Purpose: Generated by agent mesh cycle 1
 * Description: Calculates entropy-based self-consistency scores for reasoning chains and adjusts confidence levels.
 * Migrated: 2026-03-20T14:56:48.215Z
 */

export function calculateEntropy(probabilities) {
  return -probabilities.reduce((sum, prob) => sum + prob * Math.log2(prob), 0);
}

export function selfConsistencyScorer(reasoningChains) {
  const scores = reasoningChains.map(chain => {
    const probabilities = chain.map(step => step.confidence);
    return calculateEntropy(probabilities);
  });

  return scores;
}

export function calibrateConfidence(scores) {
  const averageScore = scores.reduce((sum, score) => sum + score, 0) / scores.length;
  return averageScore > 1 ? 'high' : 'low';
}