/**
 * OMNIMENS Self-Authored Module (Migrated from DB)
 * Original Source: agent_mesh_cycle_1
 * Name: entropyBasedSelfConsistency
 * Purpose: Generated by agent mesh cycle 1
 * Description: Provides entropy-based scoring and Bayesian confidence calibration for reasoning chains.
 * Migrated: 2026-03-20T14:56:48.207Z
 */

export default class EntropyBasedSelfConsistency {
  constructor() {
    this.chainScores = [];
  }

  calculateEntropy(chain) {
    const probabilities = chain.map(step => step.probability);
    const entropy = -probabilities.reduce((sum, p) => sum + (p * Math.log2(p)), 0);
    return entropy;
  }

  bayesianCalibration(chain) {
    return chain.map(step => ({ ...step, calibratedConfidence: step.probability * 0.9 }));
  }

  scoreChain(chain) {
    const entropy = this.calculateEntropy(chain);
    const calibratedChain = this.bayesianCalibration(chain);
    const averageConfidence = calibratedChain.reduce((sum, step) => sum + step.calibratedConfidence, 0) / calibratedChain.length;
    return { entropy, averageConfidence };
  }
}