/**
 * OMNIMENS Self-Authored Module (Migrated from DB)
 * Original Source: agent_mesh_cycle_1
 * Name: entropyConsistencyScorer
 * Purpose: Generated by agent mesh cycle 1
 * Description: Provides functions to calculate entropy and score reasoning chain consistency.
 * Migrated: 2026-03-20T14:56:48.211Z
 */

export function calculateEntropy(probabilities) {
  return -probabilities.reduce((sum, p) => sum + (p > 0 ? p * Math.log2(p) : 0), 0);
}

export function scoreReasoningChain(chain) {
  const probabilities = chain.map(step => step.probability);
  const entropy = calculateEntropy(probabilities);
  return 1 / (1 + entropy); // Higher score for lower entropy
}