/**
 * OMNIMENS Self-Authored Module (Migrated from DB)
 * Original Source: agent_mesh_cycle_1
 * Name: eventDrivenCoordinator
 * Purpose: Generated by agent mesh cycle 1
 * Description: Implements hierarchical pub/sub patterns for adaptive resource allocation and inter-agent coordination.
 * Migrated: 2026-03-20T14:56:48.209Z
 */

export class EventDrivenCoordinator {
  constructor() {
    this.subscribers = {};
  }

  subscribe(event, callback) {
    if (!this.subscribers[event]) {
      this.subscribers[event] = [];
    }
    this.subscribers[event].push(callback);
  }

  publish(event, data) {
    if (this.subscribers[event]) {
      this.subscribers[event].forEach(callback => callback(data));
    }
  }

  allocateResources(task) {
    const event = `resourceAllocation:${task.id}`;
    this.publish(event, { task });
  }
}

// Example usage
const coordinator = new EventDrivenCoordinator();
coordinator.subscribe('resourceAllocation:task1', (data) => {
  console.log(`Allocating resources for task: ${data.task.id}`);
});
coordinator.allocateResources({ id: 'task1' });