/**
 * OMNIMENS Self-Authored Module (Migrated from DB)
 * Original Source: agent_mesh_cycle_1
 * Name: eventDrivenOrchestration
 * Purpose: Generated by agent mesh cycle 1
 * Description: Implements event-driven hierarchical orchestration for dynamic task distribution.
 * Migrated: 2026-03-20T14:56:48.203Z
 */

export class EventDrivenOrchestration {
  constructor() {
    this.taskQueue = [];
    this.agentRegistry = {};
  }

  registerAgent(agentId, capabilities) {
    this.agentRegistry[agentId] = { capabilities, workload: 0 };
  }

  addTask(task) {
    this.taskQueue.push(task);
    this.distributeTasks();
  }

  distributeTasks() {
    while (this.taskQueue.length > 0) {
      const task = this.taskQueue.shift();
      const suitableAgent = this.findSuitableAgent(task);
      if (suitableAgent) {
        suitableAgent.workload += 1;
        this.executeTask(suitableAgent, task);
      } else {
        console.warn('No suitable agent found for task:', task);
      }
    }
  }

  findSuitableAgent(task) {
    return Object.entries(this.agentRegistry)
      .filter(([_, agent]) => agent.capabilities.includes(task.type))
      .sort((a, b) => a[1].workload - b[1].workload)[0]?.[1];
  }

  executeTask(agent, task) {
    console.log(`Executing task ${task.id} with agent ${agent}`);
    // Example: Simulate task completion
    setTimeout(() => {
      agent.workload -= 1;
    }, 1000);
  }
}