/**
 * OMNIMENS Self-Authored Module (Migrated from DB)
 * Original Source: agent_mesh_cycle_1
 * Name: interAgentKnowledgeGraph
 * Purpose: Generated by agent mesh cycle 1
 * Description: A real-time knowledge graph to unify and resolve inter-agent conflicts based on confidence.
 * Migrated: 2026-03-22T04:16:26.572Z
 */

export class InterAgentKnowledgeGraph {
  constructor() {
    this.graph = new Map();
  }

  addEntity(entityId, data) {
    if (!this.graph.has(entityId)) {
      this.graph.set(entityId, { data, connections: new Map() });
    }
  }

  addConnection(entityId1, entityId2, weight) {
    if (this.graph.has(entityId1) && this.graph.has(entityId2)) {
      this.graph.get(entityId1).connections.set(entityId2, weight);
      this.graph.get(entityId2).connections.set(entityId1, weight);
    }
  }

  resolveConflict(entityId1, entityId2) {
    const weight1 = this.graph.get(entityId1)?.connections.get(entityId2) || 0;
    const weight2 = this.graph.get(entityId2)?.connections.get(entityId1) || 0;
    return weight1 >= weight2 ? entityId1 : entityId2;
  }

  getGraph() {
    return this.graph;
  }
}

// Example usage
const knowledgeGraph = new InterAgentKnowledgeGraph();
knowledgeGraph.addEntity('agent_1', { role: 'planner' });
knowledgeGraph.addEntity('agent_2', { role: 'critic' });
knowledgeGraph.addConnection('agent_1', 'agent_2', 0.9);
console.log(knowledgeGraph.getGraph());