/**
 * OMNIMENS Self-Authored Module (Migrated from DB)
 * Original Source: agent_mesh_cycle_1
 * Name: memoryReconsolidationScheduler
 * Purpose: Generated by agent mesh cycle 1
 * Description: Scheduler for memory replay cycles during idle phases.
 * Migrated: 2026-03-20T14:56:48.205Z
 */

export class MemoryReconsolidationScheduler {
  constructor(memorySystem) {
    this.memorySystem = memorySystem;
    this.idle = false;
  }

  start() {
    setInterval(() => {
      if (this.idle) {
        this.replayMemories();
      }
    }, 60000); // Check every minute
  }

  setIdleState(isIdle) {
    this.idle = isIdle;
  }

  replayMemories() {
    const memories = this.memorySystem.getRecentMemories();
    memories.forEach(memory => {
      this.memorySystem.reinforceMemory(memory);
    });
  }
}

// Usage example:
// const scheduler = new MemoryReconsolidationScheduler(memorySystem);
// scheduler.start();
// scheduler.setIdleState(true);