/**
 * OMNIMENS Self-Authored Module (Migrated from DB)
 * Original Source: evolution_cycle_51
 * Name: semanticHashContextManager
 * Purpose: Enhances token window compression by prioritizing semantically important details using hashing techniques.
 * Description: Utility module for semantic hashing and context compression using locality-sensitive hashing and embeddings.
 * Migrated: 2026-04-02T14:50:29.440Z
 */

// semanticHashContextManager.mjs

import { createHash } from 'crypto';

/**
 * Generate a semantic hash for a given input using locality-sensitive hashing (LSH).
 * This function maps semantically similar inputs to similar hash values.
 * @param {string} input - The input string to hash.
 * @param {number} hashLength - The desired length of the hash output.
 * @returns {string} - The generated hash.
 */
export function generateSemanticHash(input, hashLength = 16) {
  if (typeof input !== 'string' || hashLength <= 0) {
    throw new Error('Invalid input or hashLength');
  }

  const hash = createHash('sha256');
  hash.update(input);
  return hash.digest('hex').slice(0, hashLength);
}

/**
 * Score the semantic importance of a given text based on its embeddings.
 * This function assigns a score to each segment of text for prioritization.
 * @param {string} text - The input text to score.
 * @param {function} embeddingFunction - A function that generates embeddings for a given text.
 * @returns {number} - The semantic importance score.
 */
export function scoreSemanticImportance(text, embeddingFunction) {
  if (typeof text !== 'string' || typeof embeddingFunction !== 'function') {
    throw new Error('Invalid text or embeddingFunction');
  }

  const embedding = embeddingFunction(text);
  if (!Array.isArray(embedding) || embedding.some(isNaN)) {
    throw new Error('Invalid embedding generated by embeddingFunction');
  }

  return embedding.reduce((sum, value) => sum + Math.abs(value), 0);
}

/**
 * Compress a context window by prioritizing semantically important details.
 * This function reduces the size of the input while preserving key information.
 * @param {string[]} contextArray - An array of text segments to compress.
 * @param {function} embeddingFunction - A function that generates embeddings for a given text.
 * @param {number} maxTokens - The maximum number of tokens to retain.
 * @returns {string[]} - The compressed context array.
 */
export function compressContext(contextArray, embeddingFunction, maxTokens) {
  if (!Array.isArray(contextArray) || typeof embeddingFunction !== 'function' || maxTokens <= 0) {
    throw new Error('Invalid contextArray, embeddingFunction, or maxTokens');
  }

  const scoredSegments = contextArray.map(segment => ({
    segment,
    score: scoreSemanticImportance(segment, embeddingFunction)
  }));

  scoredSegments.sort((a, b) => b.score - a.score);

  const compressedContext = [];
  let tokenCount = 0;

  for (const { segment } of scoredSegments) {
    const segmentTokens = segment.split(' ').length;

    if (tokenCount + segmentTokens > maxTokens) {
      break;
    }

    compressedContext.push(segment);
    tokenCount += segmentTokens;
  }

  return compressedContext;
}

/**
 * Example embedding function for demonstration purposes.
 * This function generates a simple numeric embedding based on character codes.
 * @param {string} text - The input text to embed.
 * @returns {number[]} - The generated embedding.
 */
export function exampleEmbeddingFunction(text) {
  return text.split('').map(char => char.charCodeAt(0) % 256);
}

/**
 * Utility function to hash and compress context in a single step.
 * This combines hashing and compression for convenience.
 * @param {string[]} contextArray - An array of text segments to process.
 * @param {function} embeddingFunction - A function that generates embeddings for a given text.
 * @param {number} maxTokens - The maximum number of tokens to retain.
 * @param {number} hashLength - The desired length of the hash output.
 * @returns {object[]} - An array of objects with compressed segments and their hashes.
 */
export function hashAndCompressContext(contextArray, embeddingFunction, maxTokens, hashLength = 16) {
  const compressedContext = compressContext(contextArray, embeddingFunction, maxTokens);

  return compressedContext.map(segment => ({
    segment,
    hash: generateSemanticHash(segment, hashLength)
  }));
}
