/**
 * OMNIMENS Self-Authored Module (Migrated from DB)
 * Original Source: agent_mesh_cycle_1
 * Name: spikeTimingDependentPlasticity
 * Purpose: Generated by agent mesh cycle 1
 * Description: Implements spike-timing-dependent plasticity for dynamic weight adjustments based on timing relationships.
 * Migrated: 2026-03-24T01:51:29.842Z
 */

export function applySTDP(preSynapticSpike, postSynapticSpike, weight) {
  const deltaTime = postSynapticSpike.timestamp - preSynapticSpike.timestamp;
  const learningRate = 0.01;
  if (deltaTime > 0) {
    weight += learningRate * Math.exp(-deltaTime);
  } else {
    weight -= learningRate * Math.exp(deltaTime);
  }
  return weight;
}