/**
 * OMNIMENS Self-Authored Module (Migrated from DB)
 * Original Source: agent_mesh_cycle_1
 * Name: stdpTemporalLearning
 * Purpose: Generated by agent mesh cycle 1
 * Description: Simulates spike-timing-dependent plasticity to optimize temporal sequence learning.
 * Migrated: 2026-03-22T18:47:36.136Z
 */

export function stdpUpdate(neuronPairs, learningRate = 0.01) {
  neuronPairs.forEach(({ preSynaptic, postSynaptic, spikeTimeDiff }) => {
    if (spikeTimeDiff > 0) {
      preSynaptic.weight += learningRate * Math.exp(-spikeTimeDiff);
    } else {
      preSynaptic.weight -= learningRate * Math.exp(spikeTimeDiff);
    }
  });
  return neuronPairs;
}