/**
 * OMNIMENS Self-Authored Module (Migrated from DB)
 * Original Source: agent_mesh_cycle_1
 * Name: stopPrioritizationModule
 * Purpose: Generated by agent mesh cycle 1
 * Description: Implements STOP framework to prioritize upgrades based on systemic impact and gaps.
 * Migrated: 2026-03-24T06:17:36.218Z
 */

export function prioritizeUpgrades(upgrades) {
  return upgrades.sort((a, b) => {
    const impactA = a.systemicImpact * a.capabilityGap;
    const impactB = b.systemicImpact * b.capabilityGap;
    return impactB - impactA;
  });
}