/**
 * OMNIMENS Self-Authored Module (Migrated from DB)
 * Original Source: agent_mesh_cycle_1
 * Name: weightedConfidenceVoting
 * Purpose: Generated by agent mesh cycle 1
 * Description: Implements a weighted confidence voting system to integrate agent insights dynamically.
 * Migrated: 2026-03-20T14:56:48.203Z
 */

export class WeightedConfidenceVoting {
  constructor() {
    this.agentScores = {};
  }

  addAgentScore(agentName, confidenceScore) {
    this.agentScores[agentName] = confidenceScore;
  }

  getWeightedDecision(agentInsights) {
    const weightedInsights = agentInsights.map(insight => {
      const { agent, insightValue } = insight;
      const weight = this.agentScores[agent] || 0;
      return { insightValue, weight };
    });

    const refinedDecision = weightedInsights.reduce((acc, curr) => {
      acc.sumWeightedValues += curr.insightValue * curr.weight;
      acc.totalWeight += curr.weight;
      return acc;
    }, { sumWeightedValues: 0, totalWeight: 0 });

    return refinedDecision.totalWeight > 0
      ? refinedDecision.sumWeightedValues / refinedDecision.totalWeight;
  }
}

// Usage Example
const votingSystem = new WeightedConfidenceVoting();
votingSystem.addAgentScore('Architect', 0.85);
votingSystem.addAgentScore('Mathematician', 0.75);
const decision = votingSystem.getWeightedDecision([
  { agent: 'Architect', insightValue: 1 },
  { agent: 'Mathematician', insightValue: 0.5 }
]);
console.log('Final Decision:', decision);