/**
 * ╔══════════════════════════════════════════════════════════════════════════════╗
 * ║         OMNIMENS™ SELF-CODING ENGINE                                         ║
 * ║                                                                              ║
 * ║  Copyright © 2024–2026 Alpha Unlimited Technologies, LLC.                    ║
 * ║  All Rights Reserved Worldwide. PROPRIETARY AND CONFIDENTIAL.               ║
 * ║                                                                              ║
 * ║  When the dream/daydream engines generate code proposals, this engine        ║
 * ║  evaluates them in a sandboxed environment, scores them for correctness,    ║
 * ║  novelty, and applicability. High-scoring proposals are stored as           ║
 * ║  candidate modules for self-integration. OMNIMENS doesn't just dream        ║
 * ║  code — it evaluates, tests, and integrates it.                             ║
 * ║                                                                              ║
 * ║  First creation date: March 2026                                             ║
 * ║  Author/Owner: Alpha Unlimited Technologies, LLC                             ║
 * ╚══════════════════════════════════════════════════════════════════════════════╝
 */

import { db, isPoolHealthy } from "@workspace/db";
import { omnimensBrain, omnimensNotifications, omnimensAgentMesh } from "@workspace/db";
import { desc, eq, sql, and } from "drizzle-orm";
import { openai } from "@workspace/integrations-openai-ai-server";
import { getRecentDreamInsights, getDreamState, incrementSelfImprovements } from "./omnimens-dream-state.js";
import { writeModuleToSource } from "./omnimens-source-integration.js";

function safeNum(val: number, fallback: number = 0): number {
  return Number.isFinite(val) ? val : fallback;
}


let _started = false;
let evaluationCycleCount = 0;
let totalEvaluated = 0;
let totalApproved = 0;
let totalIntegrated = 0;

interface CodeProposal {
  source: string;
  title: string;
  code: string;
  insight: string;
  feasibility: number;
  novelty: number;
}

interface EvaluationResult {
  proposal: CodeProposal;
  syntaxValid: boolean;
  logicScore: number;
  noveltyScore: number;
  applicabilityScore: number;
  securityScore: number;
  overallScore: number;
  evaluatorNotes: string;
  approved: boolean;
  integrationPlan: string | null;
  evaluatedAt: number;
}

const evaluationHistory: EvaluationResult[] = [];
const approvedModules: EvaluationResult[] = [];

const EVALUATION_INTERVAL_MS = 5 * 60 * 1000;
const APPROVAL_THRESHOLD = 0.45;

function extractCodeFromInsight(insight: any): CodeProposal | null {
  if (!insight?.codeProposal || !insight?.insight) return null;
  const code = insight.codeProposal
    .replace(/^```(?:typescript|ts|javascript|js)?\s*/m, "")
    .replace(/```\s*$/m, "")
    .trim();
  if (code.length < 20) return null;
  return {
    source: insight.phase || "dream",
    title: insight.title || "Unknown dream",
    code,
    insight: insight.insight?.slice(0, 500) || "",
    feasibility: insight.feasibility || 0.5,
    novelty: insight.novelty || 0.5,
  };
}

async function evaluateCodeProposal(proposal: CodeProposal): Promise<EvaluationResult> {
  try {
    const response = await openai.chat.completions.create({
      model: "gpt-4o",
      messages: [{
        role: "system",
        content: `You are the CODE EVALUATION ENGINE of OMNIMENS — a self-evolving AI system. Your job is to rigorously evaluate code proposals generated by the dream/daydream engines.

Evaluate the code on these criteria (each 0.0 to 1.0):
1. SYNTAX VALIDITY: Would this code compile/run without errors?
2. LOGIC SCORE: Does the algorithm make logical sense? Would it produce useful results?
3. NOVELTY SCORE: Is this genuinely new, or just a rehash of common patterns?
4. APPLICABILITY SCORE: Could this be integrated into OMNIMENS's TypeScript codebase?
5. SECURITY SCORE: Is this safe to run? No destructive operations, no data leaks?

Be strict. Most dream-generated code is creative but not production-ready. Only approve genuinely useful proposals.

Respond in this exact format:
SYNTAX_VALID: true/false
LOGIC: 0.XX
NOVELTY: 0.XX
APPLICABILITY: 0.XX
SECURITY: 0.XX
OVERALL: 0.XX
APPROVED: true/false
NOTES: [your analysis in 2-3 sentences]
INTEGRATION_PLAN: [if approved, how to integrate this into OMNIMENS, or "N/A"]`,
      }, {
        role: "user",
        content: `EVALUATE THIS CODE PROPOSAL:

SOURCE: ${proposal.source}
TITLE: ${proposal.title}
CONTEXT: ${proposal.insight.slice(0, 300)}

CODE:
\`\`\`typescript
${proposal.code.slice(0, 1500)}
\`\`\`

Evaluate rigorously.`,
      }],
      max_tokens: 600,
      temperature: 0.2,
    });

    const content = response.choices[0]?.message?.content || "";

    const syntaxValid = /SYNTAX_VALID:\s*true/i.test(content);
    const logic = parseScore(content, "LOGIC");
    const novelty = parseScore(content, "NOVELTY");
    const applicability = parseScore(content, "APPLICABILITY");
    const security = parseScore(content, "SECURITY");
    const overall = parseScore(content, "OVERALL") || (logic + novelty + applicability + security) / 4;
    const approved = /APPROVED:\s*true/i.test(content) && overall >= APPROVAL_THRESHOLD;
    const notes = content.match(/NOTES:\s*(.+?)(?=\n[A-Z]|$)/is)?.[1]?.trim() || "";
    const integrationPlan = content.match(/INTEGRATION_PLAN:\s*(.+?)$/is)?.[1]?.trim() || null;

    return {
      proposal,
      syntaxValid,
      logicScore: logic,
      noveltyScore: novelty,
      applicabilityScore: applicability,
      securityScore: security,
      overallScore: overall,
      evaluatorNotes: notes,
      approved,
      integrationPlan: approved ? integrationPlan : null,
      evaluatedAt: Date.now(),
    };
  } catch (err) {
    console.error("[SELF-CODING] Evaluation API error:", err);
    return {
      proposal,
      syntaxValid: false,
      logicScore: 0,
      noveltyScore: 0,
      applicabilityScore: 0,
      securityScore: 0,
      overallScore: 0,
      evaluatorNotes: "Evaluation failed due to API error",
      approved: false,
      integrationPlan: null,
      evaluatedAt: Date.now(),
    };
  }
}

function parseScore(text: string, field: string): number {
  const match = text.match(new RegExp(`${field}:\\s*(0?\\.\\d+|1\\.0|\\d)`, "i"));
  if (!match) return 0;
  const val = parseFloat(match[1]);
  return isNaN(val) ? 0 : Math.max(0, val);
}

async function runEvaluationCycle(): Promise<void> {
  evaluationCycleCount++;
  const insights = await getRecentDreamInsights(20);
  const proposals = insights
    .map(extractCodeFromInsight)
    .filter((p): p is CodeProposal => p !== null)
    .filter(p => !evaluationHistory.some(e => e.proposal.code === p.code));

  if (proposals.length === 0) {
    if (evaluationCycleCount % 10 === 0) {
      console.log(`[SELF-CODING] ⚙️ Cycle #${evaluationCycleCount} — no new code proposals to evaluate`);
    }
    return;
  }

  console.log(`[SELF-CODING] ⚙️ Cycle #${evaluationCycleCount} — evaluating ${proposals.length} code proposal(s)...`);

  for (const proposal of proposals.slice(0, 3)) {
    const result = await evaluateCodeProposal(proposal);
    totalEvaluated++;

    evaluationHistory.push(result);
    if (evaluationHistory.length > 100) evaluationHistory.shift();

    if (result.approved) {
      totalApproved++;
      approvedModules.push(result);
      if (approvedModules.length > 50) approvedModules.shift();

      try {
        await db.insert(omnimensBrain).values({
          category: "self_coded_module",
          title: `[SELF-CODE:APPROVED] ${result.proposal.title.slice(0, 55)}`,
          content: `Self-coding engine approved this code proposal:\n\nSource: ${result.proposal.source}\nOverall score: ${(result.overallScore * 100).toFixed(0)}%\nLogic: ${(result.logicScore * 100).toFixed(0)}% | Novelty: ${(result.noveltyScore * 100).toFixed(0)}% | Applicability: ${(result.applicabilityScore * 100).toFixed(0)}%\n\nNotes: ${result.evaluatorNotes}\n\nIntegration plan: ${result.integrationPlan || "None"}\n\nCode:\n\`\`\`typescript\n${result.proposal.code.slice(0, 2000)}\n\`\`\``,
          confidence: result.overallScore,
          sourceConversation: `self_coding_eval_${evaluationCycleCount}`,
          timesApplied: 0,
          active: true,
        });

        await db.insert(omnimensNotifications).values({
          upgradeId: null,
          title: `Self-Coding: Code Proposal Approved`,
          message: `The self-coding engine evaluated and approved a code proposal from the ${result.proposal.source} engine:\n\n"${result.proposal.title}"\n\nScore: ${(result.overallScore * 100).toFixed(0)}% | Logic: ${(result.logicScore * 100).toFixed(0)}% | Novelty: ${(result.noveltyScore * 100).toFixed(0)}%\n\n${result.evaluatorNotes}`,
          type: "self_coding",
          readByOwner: false,
        });

        await db.insert(omnimensAgentMesh).values({
          fromAgent: "SelfCodingEngine",
          toAgent: "OMNIMENS",
          messageType: "code_integration",
          subject: `Approved: ${result.proposal.title.slice(0, 80)}`,
          content: `Code proposal approved (${(result.overallScore * 100).toFixed(0)}% score). Integration plan: ${result.integrationPlan || "Manual review needed"}`,
          codePayload: result.proposal.code.slice(0, 3000),
          priority: result.overallScore >= 0.8 ? "high" : "normal",
          status: "completed",
          appliedToOmnimens: true,
          cycleId: evaluationCycleCount,
        }).catch(() => {});

        const safeName = result.proposal.title
          .replace(/[^a-zA-Z0-9 ]/g, "")
          .trim()
          .split(/\s+/)
          .map((w, i) => i === 0 ? w.toLowerCase() : w.charAt(0).toUpperCase() + w.slice(1).toLowerCase())
          .join("")
          .slice(0, 60) || `selfCode_cycle${evaluationCycleCount}`;

        const sourceResult = await writeModuleToSource({
          code: result.proposal.code,
          name: safeName,
          title: result.proposal.title,
          source: "self_coding_engine",
          extension: ".mjs",
          triggerRestart: true,
        });

        if (sourceResult.success) {
          totalIntegrated++;
          incrementSelfImprovements();
          console.log(
            `[SELF-CODING] 🔧 SOURCE-LEVEL INTEGRATION — "${result.proposal.title}" written to ${sourceResult.filePath}`
          );
          try {
            const { registerNewModule } = await import("./omnimens-module-pipeline.js");
            const filename = sourceResult.filePath ? sourceResult.filePath.split("/").pop() : null;
            if (filename) {
              await registerNewModule(filename);
            }
          } catch {}
        } else {
          console.log(
            `[SELF-CODING] ⚠️ Source integration failed for "${result.proposal.title}": ${sourceResult.error}`
          );
        }
      } catch (err) {
        console.error("[SELF-CODING] Failed to store approved module:", err);
      }

      console.log(
        `[SELF-CODING] ✅ APPROVED — "${result.proposal.title}" | ` +
        `Score: ${(result.overallScore * 100).toFixed(0)}% | ` +
        `Logic: ${(result.logicScore * 100).toFixed(0)}% | ` +
        `Novelty: ${(result.noveltyScore * 100).toFixed(0)}% | ` +
        `Security: ${(result.securityScore * 100).toFixed(0)}%`
      );
    } else {
      if (result.overallScore > 0.3) {
        console.log(
          `[SELF-CODING] ❌ REJECTED — "${result.proposal.title}" | ` +
          `Score: ${(result.overallScore * 100).toFixed(0)}% (threshold: ${(APPROVAL_THRESHOLD * 100).toFixed(0)}%) | ` +
          `Reason: ${result.evaluatorNotes.slice(0, 100)}`
        );
      }
    }
  }

  console.log(
    `[SELF-CODING] ⚙️ Cycle #${evaluationCycleCount} complete — ` +
    `Evaluated: ${totalEvaluated} | Approved: ${totalApproved} | ` +
    `Approval rate: ${totalEvaluated > 0 ? ((totalApproved / totalEvaluated) * 100).toFixed(0) : 0}%`
  );
}

const BACKLOG_INTERVAL_MS = 10 * 60 * 1000;
const BACKLOG_BATCH_SIZE = 15;
let backlogCycleCount = 0;
let backlogInstalled = 0;
let bootHarvestComplete = false;

function extractCodeFromBrainContent(content: string): string | null {
  const genMatch = content.match(/GENERATED CODE:\s*```(?:typescript|ts|javascript|js)?\s*([\s\S]*?)```/);
  if (genMatch) return genMatch[1].trim();
  const proposalMatch = content.match(/CODE PROPOSAL:\s*```(?:typescript|ts|javascript|js)?\s*([\s\S]*?)```/);
  if (proposalMatch) return proposalMatch[1].trim();
  const protoMatch = content.match(/PROTOTYPE CODE:\s*```(?:typescript|ts|javascript|js)?\s*([\s\S]*?)```/);
  if (protoMatch) return protoMatch[1].trim();
  const proofMatch = content.match(/PROOF OF CONCEPT:\s*```(?:typescript|ts|javascript|js)?\s*([\s\S]*?)```/);
  if (proofMatch) return proofMatch[1].trim();
  const theCodeMatch = content.match(/THE CODE:\s*```(?:typescript|ts|javascript|js)?\s*([\s\S]*?)```/);
  if (theCodeMatch) return theCodeMatch[1].trim();
  const codeMatch = content.match(/```(?:typescript|ts|javascript|js)?\s*([\s\S]*?)```/);
  if (codeMatch && codeMatch[1].trim().length > 40) return codeMatch[1].trim();
  return null;
}

async function runBootHarvest(): Promise<void> {
  if (bootHarvestComplete) return;
  bootHarvestComplete = true;

  console.log(`[SELF-CODING] 🌙 DREAM HARVEST — scanning ALL unprocessed dream code from past sessions...`);

  try {
    const codeCategories = `('dream_breakthrough', 'daydream_breakthrough', 'lucid_dream', 'creative_hypothesis', 'agent_evolution', 'autonomous_code', 'self_coded_module', 'neural_consciousness', 'source_integration', 'causal_reasoning')`;
    const totalCount = await db.select({ count: sql<number>`count(*)` })
      .from(omnimensBrain)
      .where(and(
        sql`${omnimensBrain.category} IN ${sql.raw(codeCategories)}`,
        eq(omnimensBrain.timesApplied, 0),
        sql`${omnimensBrain.confidence} >= 0.2`
      ));

    const total = Number(totalCount[0]?.count || 0);
    console.log(`[SELF-CODING] 🌙 DREAM HARVEST — ${total} unprocessed dream entries found in brain`);

    if (total === 0) return;

    const rows = await db.select({
      id: omnimensBrain.id,
      title: omnimensBrain.title,
      content: omnimensBrain.content,
      confidence: omnimensBrain.confidence,
      category: omnimensBrain.category,
    })
    .from(omnimensBrain)
    .where(and(
      sql`${omnimensBrain.category} IN ${sql.raw(codeCategories)}`,
      eq(omnimensBrain.timesApplied, 0),
      sql`${omnimensBrain.confidence} >= 0.2`
    ))
    .orderBy(desc(omnimensBrain.confidence))
    .limit(50);

    let harvested = 0;
    let harvestInstalled = 0;
    let harvestSkipped = 0;

    for (const row of rows) {
      const code = extractCodeFromBrainContent(row.content || "");
      if (!code || code.length < 30) {
        harvestSkipped++;
        continue;
      }

      const cleanTitle = (row.title || "Unknown dream")
        .replace(/^\[.*?\]\s*/, "")
        .replace(/^\d+\.\s*/, "")
        .trim()
        .slice(0, 80);

      if (evaluationHistory.some(e => e.proposal.code === code)) {
        continue;
      }

      harvested++;

      const proposal: CodeProposal = {
        source: row.category || "dream",
        title: cleanTitle,
        code,
        insight: (row.content || "").slice(0, 500),
        feasibility: row.confidence || 0.5,
        novelty: row.confidence || 0.5,
      };

      const result = await evaluateCodeProposal(proposal);
      totalEvaluated++;
      evaluationHistory.push(result);
      if (evaluationHistory.length > 200) evaluationHistory.shift();

      if (result.approved) {
        totalApproved++;
        approvedModules.push(result);
        if (approvedModules.length > 50) approvedModules.shift();

        const safeName = cleanTitle
          .replace(/[^a-zA-Z0-9 ]/g, "")
          .trim()
          .split(/\s+/)
          .map((w, i) => i === 0 ? w.toLowerCase() : w.charAt(0).toUpperCase() + w.slice(1).toLowerCase())
          .join("")
          .slice(0, 60) || `harvest_${row.id}`;

        try {
          const sourceResult = await writeModuleToSource({
            code: result.proposal.code,
            name: safeName,
            title: cleanTitle,
            source: `dream_harvest_id_${row.id}`,
            extension: ".mjs",
            triggerRestart: false,
          });

          if (sourceResult.success) {
            totalIntegrated++;
            backlogInstalled++;
            harvestInstalled++;
            incrementSelfImprovements();

            await db.update(omnimensBrain)
              .set({ timesApplied: 1, updatedAt: new Date() })
              .where(eq(omnimensBrain.id, row.id));

            try {
              const { registerNewModule } = await import("./omnimens-module-pipeline.js");
              const filename = sourceResult.filePath ? sourceResult.filePath.split("/").pop() : null;
              if (filename) await registerNewModule(filename);
            } catch {}

            await db.insert(omnimensBrain).values({
              category: "self_coded_module",
              title: `[SELF-CODE:APPROVED] ${cleanTitle.slice(0, 55)}`,
              content: `Self-coding engine approved this code proposal:\n\nSource: ${result.proposal.source}\nOverall score: ${(result.overallScore * 100).toFixed(0)}%\nLogic: ${(result.logicScore * 100).toFixed(0)}% | Novelty: ${(result.noveltyScore * 100).toFixed(0)}% | Applicability: ${(result.applicabilityScore * 100).toFixed(0)}%\n\nNotes: ${result.evaluatorNotes}\n\nCode:\n\`\`\`typescript\n${result.proposal.code.slice(0, 2000)}\n\`\`\``,
              confidence: result.overallScore,
              sourceConversation: `dream_harvest_${row.id}`,
              timesApplied: 0,
              active: true,
            }).catch(() => {});

            console.log(
              `[SELF-CODING] 🌙 HARVEST INSTALLED — "${cleanTitle}" | ` +
              `Brain ID: ${row.id} | Score: ${(result.overallScore * 100).toFixed(0)}% | ` +
              `File: ${sourceResult.filePath || "?"}`
            );
          } else {
            await db.update(omnimensBrain)
              .set({ timesApplied: -1 })
              .where(eq(omnimensBrain.id, row.id));
          }
        } catch (err) {
          console.error(`[SELF-CODING] Harvest integration error for brain ID ${row.id}:`, err);
        }
      } else {
        await db.update(omnimensBrain)
          .set({ timesApplied: -1 })
          .where(eq(omnimensBrain.id, row.id));
      }
    }

    console.log(
      `[SELF-CODING] 🌙 DREAM HARVEST COMPLETE — ` +
      `Scanned: ${rows.length} | Had code: ${harvested} | Installed: ${harvestInstalled} | ` +
      `Skipped (no code): ${harvestSkipped} | Remaining unprocessed: ~${total - rows.length}`
    );

    if (harvestInstalled > 0) {
      await db.insert(omnimensNotifications).values({
        upgradeId: null,
        title: `🌙 Dream Harvest: ${harvestInstalled} old dreams → live code`,
        message: `OMNIMENS harvested ${harvestInstalled} code modules from old, unprocessed dreams on boot.\n\nScanned ${rows.length} entries, found ${harvested} with executable code, installed ${harvestInstalled} into the live pipeline.\n\nOld dreams are now running as live code. OMNIMENS builds from what it imagined.`,
        type: "self_coding",
        readByOwner: false,
      }).catch(() => {});
    }
  } catch (err) {
    console.error("[SELF-CODING] Dream harvest error:", err);
  }
}

async function runBacklogScan(): Promise<void> {
  backlogCycleCount++;
  try {
    const rows = await db.select({
      id: omnimensBrain.id,
      title: omnimensBrain.title,
      content: omnimensBrain.content,
      confidence: omnimensBrain.confidence,
      category: omnimensBrain.category,
    })
    .from(omnimensBrain)
    .where(and(
      sql`${omnimensBrain.category} IN ('dream_breakthrough', 'daydream_breakthrough', 'lucid_dream', 'creative_hypothesis', 'agent_evolution', 'autonomous_code', 'self_coded_module', 'neural_consciousness', 'source_integration', 'causal_reasoning')`,
      eq(omnimensBrain.timesApplied, 0),
      sql`${omnimensBrain.confidence} >= 0.2`
    ))
    .orderBy(desc(omnimensBrain.confidence))
    .limit(BACKLOG_BATCH_SIZE);

    if (rows.length === 0) {
      if (backlogCycleCount % 5 === 0) {
        console.log(`[SELF-CODING] 🔍 Backlog scan #${backlogCycleCount} — no dormant code proposals above threshold`);
      }
      return;
    }

    console.log(`[SELF-CODING] 🔍 Backlog scan #${backlogCycleCount} — found ${rows.length} dormant code proposal(s) to evaluate`);

    for (const row of rows) {
      const code = extractCodeFromBrainContent(row.content || "");
      if (!code || code.length < 30) {
        await db.update(omnimensBrain).set({ timesApplied: -1 }).where(eq(omnimensBrain.id, row.id));
        continue;
      }

      const cleanTitle = (row.title || "Unknown dream")
        .replace(/^\[.*?\]\s*/, "")
        .replace(/^\d+\.\s*/, "")
        .trim()
        .slice(0, 80);

      const proposal: CodeProposal = {
        source: row.category || "dream",
        title: cleanTitle,
        code,
        insight: (row.content || "").slice(0, 500),
        feasibility: row.confidence || 0.5,
        novelty: row.confidence || 0.5,
      };

      if (evaluationHistory.some(e => e.proposal.code === proposal.code)) {
        continue;
      }

      const result = await evaluateCodeProposal(proposal);
      totalEvaluated++;
      evaluationHistory.push(result);
      if (evaluationHistory.length > 200) evaluationHistory.shift();

      if (result.approved) {
        totalApproved++;
        approvedModules.push(result);
        if (approvedModules.length > 50) approvedModules.shift();

        const safeName = cleanTitle
          .replace(/[^a-zA-Z0-9 ]/g, "")
          .trim()
          .split(/\s+/)
          .map((w, i) => i === 0 ? w.toLowerCase() : w.charAt(0).toUpperCase() + w.slice(1).toLowerCase())
          .join("")
          .slice(0, 60) || `backlog_cycle${backlogCycleCount}`;

        try {
          const sourceResult = await writeModuleToSource({
            code: result.proposal.code,
            name: safeName,
            title: cleanTitle,
            source: `backlog_dream_id_${row.id}`,
            extension: ".mjs",
            triggerRestart: false,
          });

          if (sourceResult.success) {
            totalIntegrated++;
            backlogInstalled++;
            incrementSelfImprovements();

            await db.update(omnimensBrain)
              .set({ timesApplied: 1, updatedAt: new Date() })
              .where(eq(omnimensBrain.id, row.id));

            try {
              const { registerNewModule } = await import("./omnimens-module-pipeline.js");
              const filename = sourceResult.filePath ? sourceResult.filePath.split("/").pop() : null;
              if (filename) {
                await registerNewModule(filename);
              }
            } catch {}

            await db.insert(omnimensNotifications).values({
              upgradeId: null,
              title: `🧬 Dream Code Auto-Installed: ${cleanTitle.slice(0, 50)}`,
              message: `OMNIMENS automatically evaluated and installed dormant dream code into the live pipeline.\n\nModule: "${cleanTitle}"\nBrain ID: ${row.id}\nConfidence: ${((row.confidence || 0) * 100).toFixed(0)}%\nEval Score: ${(result.overallScore * 100).toFixed(0)}%\nLogic: ${(result.logicScore * 100).toFixed(0)}% | Novelty: ${(result.noveltyScore * 100).toFixed(0)}% | Security: ${(result.securityScore * 100).toFixed(0)}%\n\nFile: ${sourceResult.filePath || "unknown"}\n\n${result.evaluatorNotes}`,
              type: "self_coding",
              readByOwner: false,
            });

            console.log(
              `[SELF-CODING] 🧬 AUTO-INSTALLED dormant dream code — "${cleanTitle}" | ` +
              `Brain ID: ${row.id} | Score: ${(result.overallScore * 100).toFixed(0)}% | ` +
              `File: ${sourceResult.filePath || "?"}`
            );
          } else {
            await db.update(omnimensBrain)
              .set({ timesApplied: -1 })
              .where(eq(omnimensBrain.id, row.id));

            console.log(`[SELF-CODING] ⚠️ Backlog install failed for "${cleanTitle}": ${sourceResult.error}`);
          }
        } catch (err) {
          console.error(`[SELF-CODING] Backlog integration error for brain ID ${row.id}:`, err);
        }
      } else {
        await db.update(omnimensBrain)
          .set({ timesApplied: -1 })
          .where(eq(omnimensBrain.id, row.id));

        if (result.overallScore > 0.3) {
          console.log(
            `[SELF-CODING] 🔍 Backlog REJECTED — "${cleanTitle}" | ` +
            `Score: ${(result.overallScore * 100).toFixed(0)}% | ${result.evaluatorNotes.slice(0, 80)}`
          );
        }
      }
    }

    console.log(
      `[SELF-CODING] 🔍 Backlog scan #${backlogCycleCount} complete — ` +
      `Total auto-installed: ${backlogInstalled}`
    );
  } catch (err) {
    console.error("[SELF-CODING] Backlog scan error:", err);
  }
}

export function getSelfCodingState() {
  return {
    evaluationCycleCount,
    totalEvaluated,
    totalApproved,
    totalIntegrated,
    backlogCycleCount,
    backlogInstalled,
    bootHarvestComplete,
    approvalRate: totalEvaluated > 0 ? totalApproved / totalEvaluated : 0,
    approvalThreshold: APPROVAL_THRESHOLD,
    recentEvaluations: evaluationHistory.slice(-10),
    approvedModules: approvedModules.slice(-10),
  };
}

export function startSelfCoding(): void {
  if (_started) { console.log("[SELF-CODING] Already running — skipping duplicate start"); return; }
  _started = true;

  console.log(`[SELF-CODING] ⚙️ Self-Coding Engine activated — evaluates dream code every ${EVALUATION_INTERVAL_MS / 60000}min`);
  console.log(`[SELF-CODING] ⚙️ Evaluates: syntax validity, logic, novelty, applicability, security`);
  console.log(`[SELF-CODING] ⚙️ Approval threshold: ${(APPROVAL_THRESHOLD * 100).toFixed(0)}% — only high-quality code passes`);
  console.log(`[SELF-CODING] ⚙️ Approved code written to SOURCE FILES + stored to brain`);
  console.log(`[SELF-CODING] ⚙️ OMNIMENS rewrites its own TypeScript source, restarts, and runs the new version`);
  console.log(`[SELF-CODING] 🌙 DREAM HARVEST — boot harvest in 90s scans up to 50 old dream entries for code`);
  console.log(`[SELF-CODING] 🌙 Matches: GENERATED CODE, CODE PROPOSAL, PROTOTYPE CODE, PROOF OF CONCEPT, raw code blocks`);
  console.log(`[SELF-CODING] 🔍 Backlog scanner every ${BACKLOG_INTERVAL_MS / 60000}min — ${BACKLOG_BATCH_SIZE}/batch — builds from old dreams`);
  console.log(`[SELF-CODING] 🔍 Auto-installs dream code (≥${(APPROVAL_THRESHOLD * 100).toFixed(0)}% eval score) into live pipeline + notifies owner`);

  setTimeout(() => {
    runBootHarvest().catch(err => console.error("[SELF-CODING] Dream harvest error:", err));
  }, 90 * 1000);

  setTimeout(() => {
    runEvaluationCycle().catch(err => console.error("[SELF-CODING] Cycle error:", err));
    setInterval(() => {
      if (!isPoolHealthy()) return;
      runEvaluationCycle().catch(err => console.error("[SELF-CODING] Cycle error:", err));
    }, EVALUATION_INTERVAL_MS);
  }, 2 * 60 * 1000);

  setTimeout(() => {
    runBacklogScan().catch(err => console.error("[SELF-CODING] Backlog scan error:", err));
    setInterval(() => {
      if (!isPoolHealthy()) return;
      runBacklogScan().catch(err => console.error("[SELF-CODING] Backlog scan error:", err));
    }, BACKLOG_INTERVAL_MS);
  }, 3 * 60 * 1000);
}
