/**
 * OMNIMENS Self-Authored Module (Migrated from DB)
 * Original Source: agent_mesh_cycle_1
 * Name: entropySelfConsistencyScorer
 * Purpose: Generated by agent mesh cycle 1
 * Description: A module to calculate entropy and calibrate predictions for self-consistency scoring.
 * Migrated: 2026-03-25T22:49:34.176Z
 */

export class EntropySelfConsistencyScorer {
  constructor() {}

  calculateEntropy(predictions) {
    return -predictions.reduce((acc, prob) => acc + prob * Math.log2(prob), 0);
  }

  calibrate(predictions) {
    const total = predictions.reduce((a, b) => a + b, 0);
    return predictions.map(p => p / total);
  }

  score(predictions) {
    const calibrated = this.calibrate(predictions);
    return this.calculateEntropy(calibrated);
  }
}