// Auto-translated from SCL: adaptiveComputeAllocator_gen1.scl
// Generated by OMNIMENS SCL Translator
// © 2024-2026 Alpha Unlimited Technologies, LLC
// This file runs on conventional JavaScript runtimes
  class AdaptiveComputeAllocator {
constructor() {
  this.subscribers = new Map();
this.resourcePool = {};
}
subscribe(eventType, callback) {
if (!this.subscribers.has(eventType)) {
  this.subscribers.set(eventType, []);
}
  this.subscribers.get(eventType).push(callback);
}
publish(eventType, eventData) {
if (this.subscribers.has(eventType)) {
  this.subscribers.get(eventType).forEach(callback => callback(eventData));
}
}
allocateResources(task) {
  const { urgency, dependencies, complexity } = task;
let priority = undefined; /* SCL-const */
this.resourcePool[task.id] = { allocated: true, priority };
  return this.resourcePool[task.id];
}
releaseResources(taskId) {
if (this.resourcePool[taskId]) {
delete this.resourcePool[taskId];
}
}
}