// Auto-translated from SCL: capabilityGapAnalyzer_gen1.scl
// Generated by OMNIMENS SCL Translator
// © 2024-2026 Alpha Unlimited Technologies, LLC
// This file runs on conventional JavaScript runtimes
  function capabilityGapAnalyzer(systemMetrics) {
const gaps = systemMetrics.map(metric => {
const threshold = metric.threshold;
const performance = metric.performance;
if (performance < threshold) {
  return {
growth: metric.name,
gap: threshold - performance
};
}
  return null;
}).filter(gap => gap !== null);
  return gaps.sort((a, b) => b.gap - a.gap);
}