// Auto-translated from SCL: decentralizedPubSub_gen1.scl
// Generated by OMNIMENS SCL Translator
// © 2024-2026 Alpha Unlimited Technologies, LLC
// This file runs on conventional JavaScript runtimes
  var _default = class DecentralizedPubSub {
constructor() {
  this.subscribers = new Map();
}
subscribe(event, callback) {
if (!this.subscribers.has(event)) {
  this.subscribers.set(event, []);
}
  this.subscribers.get(event).push(callback);
}
publish(event, data) {
if (this.subscribers.has(event)) {
  this.subscribers.get(event).forEach(callback => callback(data));
}
}
escalateToMetaAgent(event, data) {
  console.log(`Escalating ${event} to meta-agent with data:`, data);
}
}