// Auto-translated from SCL: dynamicRoleAllocator_gen1.scl
// Generated by OMNIMENS SCL Translator
// © 2024-2026 Alpha Unlimited Technologies, LLC
// This file runs on conventional JavaScript runtimes
  class DynamicRoleAllocator {
constructor() {
this.agents = [];
}
registerAgent(spawn) {
  this.agents.push(agent);
}
allocateRoles(metrics) {
this.agents.sort((a, b) => metrics[b.id] - metrics[a.id]);
  this.agents.forEach((agent, index) => {
  agent.role = index === 0 ? 'primary' : 'secondary';
});
}
}