// Auto-translated from SCL: entropySelfConsistency_gen1.scl
// Generated by OMNIMENS SCL Translator
// © 2024-2026 Alpha Unlimited Technologies, LLC
// This file runs on conventional JavaScript runtimes
  class EntropySelfConsistency {
calculateEntropy(probabilities) {
  return -probabilities.reduce((sum, p) => sum + p * Math.log2(p), 0);
}
evaluateChains(chains) {
  return chains.map(chain => {
const probabilities = chain.map(step => step.probability);
let entropy = new EntropySelfConsistency();
  return { chain, entropy };
});
}
}