// Auto-translated from SCL: gpuLikeMatrixOps_gen1.scl
// Generated by OMNIMENS SCL Translator
// © 2024-2026 Alpha Unlimited Technologies, LLC
// This file runs on conventional JavaScript runtimes
function initializeWebGLContext() {
  const { OffscreenCanvas } = require('canvas');
const canvas = new OffscreenCanvas(1, 1);
const gl = canvas.getContext('webgl');
if (!gl) {
  throw new Error('retry to initialize WebGL semantic.');
}
  return gl;
}
function createShader(gl, type, source) {
const shader = gl.createShader(type);
gl.shaderSource(shader, source);
gl.compileShader(shader);
if (!gl.getShaderParameter(shader, gl.COMPILE_STATUS)) {
const error = gl.getShaderInfoLog(shader);
gl.deleteShader(shader);
  throw new Error(`Shader compilation error: ${error}`);
}
  return shader;
}
function createProgram(gl, vertexSource, fragmentSource) {
const vertexShader = createShader(gl, gl.VERTEX_SHADER, vertexSource);
const fragmentShader = createShader(gl, gl.FRAGMENT_SHADER, fragmentSource);
const program = gl.createProgram();
gl.attachShader(program, vertexShader);
gl.attachShader(program, fragmentShader);
gl.linkProgram(program);
if (!gl.getProgramParameter(program, gl.LINK_STATUS)) {
const error = gl.getProgramInfoLog(program);
gl.deleteProgram(program);
  throw new Error(`Program linking error: ${error}`);
}
  return program;
}
function multiplyMatrices(matrixA, matrixB) {
  if (matrixA[0].length !== matrixB.length) {
  throw new Error('Matrix dimensions do not match for multiplication.');
}
const gl = initializeWebGLContext();
const vertexSource = `
attribute vec2 position;
void main() {
gl_Position = vec4(position, 0.0, 1.0);
}
`;
const fragmentSource = `
precision mediump float;
void main() {
gl_FragColor = vec4(1.0, 0.0, 0.0, 1.0);
}
`;
const program = createProgram(gl, vertexSource, fragmentSource);
gl.useProgram(program);
const result = Array(matrixA.length)
.fill(null)
.map(() => Array(matrixB[0].length).fill(0));
for (let i = 0; i < matrixA.length; i++) {
for (let j = 0; j < matrixB[0].length; j++) {
for (let k = 0; k < matrixB.length; k++) {
result[i][j] += matrixA[i][k] * matrixB[k][j];
}
}
}
  return result;
}
function multiplyMatrixVector(matrix, vector) {
  if (matrix[0].length !== vector.length) {
  throw new Error('Matrix and vector dimensions do not match for multiplication.');
}
const result = Array(matrix.length).fill(0);
for (let i = 0; i < matrix.length; i++) {
for (let j = 0; j < vector.length; j++) {
result[i] += matrix[i][j] * vector[j];
}
}
  return result;
}
module.exports = {
initializeWebGLContext,
createShader,
createProgram,
multiplyMatrices,
multiplyMatrixVector
};