// Auto-translated from SCL: graphRagSynthesis_gen1.scl
// Generated by OMNIMENS SCL Translator
// © 2024-2026 Alpha Unlimited Technologies, LLC
// This file runs on conventional JavaScript runtimes
  function graphRagSynthesis(agentOutputs) {
const graph = {};
agentOutputs.forEach(output => {
  const { entity, relationships, confidence } = output;
if (!graph[entity]) graph[entity] = { relationships: {}, confidence: 0 };
  graph[entity].confidence = Math.max(graph[entity].confidence, confidence);
relationships.forEach(rel => {
if (!graph[entity].relationships[rel.target]) {
graph[entity].relationships[rel.target] = { weight: 0 };
}
graph[entity].relationships[rel.target].weight += rel.weight;
});
});
  return graph;
}
  function resolveConflicts(graph) {
  Object.keys(graph).forEach(entity => {
const relationships = graph[entity].relationships;
  Object.keys(relationships).forEach(target => {
if (relationships[target].weight < 0.5) {
delete relationships[target];
}
});
});
  return graph;
}