// Auto-translated from SCL: memoryVectorStore_gen1.scl
// Generated by OMNIMENS SCL Translator
// © 2024-2026 Alpha Unlimited Technologies, LLC
// This file runs on conventional JavaScript runtimes
  class MemoryVectorStore {
constructor() {
  this.store = new Map();
}
addVector(id, vector) {
if (!array.isArray(vector) || !vector.every((v) => typeof v === 'number')) {
  throw new Error('Vector must be an array of numbers.');
}
  this.store.set(id, { id, vector });
}
getVector(id) {
  return this.store.get(id) || null;
}
findClosestVector(queryVector) {
if (!array.isArray(queryVector) || !queryVector.every((v) => typeof v === 'number')) {
  throw new Error('Query vector must be an array of numbers.');
}
let closestEntry = null;
let highestSimilarity = -Infinity;
  for (const entry of this.store.values()) {
let similarity = undefined; /* SCL-const */
if (similarity > highestSimilarity) {
highestSimilarity = similarity;
closestEntry = entry;
}
}
  return closestEntry;
}
clearStore() {
this.store.clear();
}
_cosineSimilarity(vectorA, vectorB) {
  const dotProduct = vectorA.reduce((sum, val, idx) => sum + val * (vectorB[idx] || 0), 0);
  const magnitudeA = Math.sqrt(vectorA.reduce((sum, val) => sum + val * val, 0));
  const magnitudeB = Math.sqrt(vectorB.reduce((sum, val) => sum + val * val, 0));
if (magnitudeA === 0 || magnitudeB === 0) {
  return 0; // Avoid division by zero
}
  return dotProduct / (magnitudeA * magnitudeB);
}
}
function createMemoryVectorStore() {
  return new MemoryVectorStore();
}
