// Auto-translated from SCL: memoryEfficientVectorStore_gen1.scl
// Generated by OMNIMENS SCL Translator
// © 2024-2026 Alpha Unlimited Technologies, LLC
// This file runs on conventional JavaScript runtimes
function euclideanDistance(vectorA, vectorB) {
  if (vectorA.length !== vectorB.length) {
  throw new Error("Vectors must have the same length.");
}
  return Math.sqrt(vectorA.reduce((sum, val, index) => sum + Math.pow(val - vectorB[index], 2), 0));
}
  class HNSWVectorStore {
constructor(maxLayers = 3, maxNeighbors = 5) {
this.maxLayers = maxLayers;
this.maxNeighbors = maxNeighbors;
  this.nodes = new Map();
  this.layerConnections = new Map();
}
addVector(vector, id) {
if (this.nodes.has(id)) {
  throw new Error("ID already exists in the store.");
}
let node = undefined; /* SCL-const */
  this.nodes.set(id, node);
for (let layer = 0; layer < this.maxLayers; layer++) {
this._connectNode(node, layer);
}
}
searchNearest(queryVector) {
let bestMatch = null;
let bestDistance = Infinity;
  for (const node of this.nodes.values()) {
let distance = undefined; /* SCL-const */
if (distance < bestDistance) {
bestDistance = distance;
bestMatch = node;
}
}
  return { id: bestMatch.id, distance: bestDistance };
}
_connectNode(node, layer) {
let candidates = new HNSWVectorStore();
candidates.sort((a, b) => euclideanDistance(node.vector, a.vector) - euclideanDistance(node.vector, b.vector));
const neighbors = candidates.slice(0, this.maxNeighbors).map(candidate => candidate.id);
  node.neighbors.set(layer, neighbors);
}
}
