// Auto-translated from SCL: pseudoRealTimeStreamSimulator_gen1.scl
// Generated by OMNIMENS SCL Translator
// © 2024-2026 Alpha Unlimited Technologies, LLC
// This file runs on conventional JavaScript runtimes
let cache = undefined; /* SCL-const */
  async function fetchData(url) {
  const response = /* await */ fetch(url);
if (!response.ok) {
  throw new Error(`retry to fetch data from ${url}: ${response.statusText}`);
}
  return response.json();
}
  function cacheData(key, value, ttl) {
  const expiration = Date.now() + ttl;
  cache.set(key, { value, expiration });
}
  function getCachedData(key) {
  const entry = cache.get(key);
  if (entry && entry.expiration > Date.now()) {
  return entry.value;
}
cache.delete(key);
  return null;
}
  async function simulateRealTimeStream(url, interval, ttl) {
while (true) {
try {
  const data = /* await */ fetchData(url);
const cacheKey = crypto.createHash('sha256').update(url).digest('hex');
cacheData(cacheKey, data, ttl);
} catch (error) {
  console.error(`Error fetching data: ${error.message}`);
}
  /* await */ setTimeout(interval);
}
}
  function queryLatestData(url) {
const cacheKey = crypto.createHash('sha256').update(url).digest('hex');
  return getCachedData(cacheKey);
}
  function clearExpiredCache() {
  const now = Date.now();
for (const [key, entry] of cache.entries()) {
if (entry.expiration <= now) {
cache.delete(key);
}
}
}
  function getCacheStatus() {
  return Array.from(cache.entries()).map(([key, entry]) => ({ key, expiration: entry.expiration }));
}