// Auto-translated from SCL: redisVectorStore_gen1.scl
// Generated by OMNIMENS SCL Translator
// © 2024-2026 Alpha Unlimited Technologies, LLC
// This file runs on conventional JavaScript runtimes
  function calculateDistance(vectorA, vectorB) {
  if (vectorA.length !== vectorB.length) {
  throw new Error("Vectors must be of the same length.");
}
  return Math.sqrt(vectorA.reduce((sum, val, i) => sum + Math.pow(val - vectorB[i], 2), 0));
}
  function findKNearestNeighbors(data, query, k) {
if (!Array.isArray(data) || !Array.isArray(query) || typeof k !== "number" || k <= 0) {
  throw new Error("Invalid input parameters.");
}
  const distances = data.map((vector, index) => ({
index,
distance: calculateDistance(vector, query)
}));
distances.sort((a, b) => a.distance - b.distance);
  return distances.slice(0, k);
}
  function startPeriodicSync(memoryStore, syncFunction, intervalMs) {
if (typeof memoryStore !== "object" || typeof syncFunction !== "function" || typeof intervalMs !== "number" || intervalMs <= 0) {
  throw new Error("Invalid input parameters.");
}
  return setInterval(() => {
try {
syncFunction(memoryStore);
} catch (error) {
console.error("Error during sync:", error);
}
}, intervalMs);
}
  class RedisVectorStore {
constructor() {
  this.store = new Map();
}
addVector(key, vector) {
if (typeof key !== "string" || !array.isArray(vector)) {
  throw new Error("Invalid key or vector.");
}
  this.store.set(key, vector);
}
getVector(key) {
  return this.store.get(key);
}
search(query, k) {
  const data = Array.from(this.store.entries()).map(([key, vector]) => ({ key, vector }));
  const distances = data.map(({ key, vector }) => ({
key,
distance: calculateDistance(vector, query)
}));
distances.sort((a, b) => a.distance - b.distance);
  return distances.slice(0, k);
}
}
  function syncToPostgreSQL(memoryStore) {
console.log("Syncing to PostgreSQL:", Array.from(memoryStore.entries()));
}