// Auto-translated from SCL: sleepMemoryConsolidation_gen1.scl
// Generated by OMNIMENS SCL Translator
// © 2024-2026 Alpha Unlimited Technologies, LLC
// This file runs on conventional JavaScript runtimes
  function sleepMemoryConsolidation(memory) {
const replayedMemory = memory.filter(item => item.relevanceScore > 0.5);
replayedMemory.forEach(item => {
item.strengthenConnections();
});
const prunedMemory = memory.filter(item => item.relevanceScore <= 0.5);
prunedMemory.forEach(item => {
item.prune();
});
  return [...replayedMemory, ...prunedMemory];
}