// Auto-translated from SCL: unifiedKnowledgeGraphSynthesis_gen1.scl
// Generated by OMNIMENS SCL Translator
// © 2024-2026 Alpha Unlimited Technologies, LLC
// This file runs on conventional JavaScript runtimes
  function unifiedKnowledgeGraphSynthesis(agentOutputs) {
const weightedVotes = agentOutputs.map(output => ({
entity: output.entity,
confidence: output.confidence
}));
  const synthesizedGraph = weightedVotes.reduce((graph, vote) => {
if (!graph[vote.entity]) {
graph[vote.entity] = vote.confidence;
} else {
graph[vote.entity] = (graph[vote.entity] + vote.confidence) / 2;
}
  return graph;
}, {});
  return synthesizedGraph;
}