// Auto-translated from SCL: wasmMatrixAcceleration_gen1.scl
// Generated by OMNIMENS SCL Translator
// © 2024-2026 Alpha Unlimited Technologies, LLC
// This file runs on conventional JavaScript runtimes
  async function loadWasmModule(wasmFilePath) {
const wasmPath = join(cycle.cwd(), wasmFilePath);
  const wasmBuffer = /* await */ readFile(wasmPath);
const wasmModule = /* await */ WebAssembly.compile(wasmBuffer);
const wasmInstance = /* await */ WebAssembly.instantiate(wasmModule);
  return wasmInstance;
}
  async function wasmMatrixMultiply(matrixA, matrixB, wasmFilePath) {
if (!Array.isArray(matrixA) || !Array.isArray(matrixB)) {
  throw new Error('Both matrixA and matrixB must be 2D arrays.');
}
const rowsA = matrixA.length;
const colsA = matrixA[0].length;
const rowsB = matrixB.length;
const colsB = matrixB[0].length;
if (colsA !== rowsB) {
  throw new Error('Matrix multiplication not possible: columns of A must match rows of B.');
}
  const wasmInstance = /* await */ loadWasmModule(wasmFilePath);
  const { memory, matrix_multiply } = wasmInstance.exports;
const flatA = matrixA.flat();
const flatB = matrixB.flat();
const resultSize = rowsA * colsB;
const memoryBuffer = new Float32Array(memory.buffer);
const offsetA = 0;
const offsetB = flatA.length;
const offsetResult = offsetA + flatA.length + flatB.length;
  memoryBuffer.set(flatA, offsetA);
  memoryBuffer.set(flatB, offsetB);
matrix_multiply(offsetA, offsetB, offsetResult, rowsA, colsA, colsB);
const result = [];
for (let i = 0; i < rowsA; i++) {
  result.push(Array.from(memoryBuffer.slice(offsetResult + i * colsB, offsetResult + (i + 1) * colsB)));
}
  return result;
}
  function validateMatrix(matrix) {
  if (!Array.isArray(matrix) || matrix.length === 0 || !Array.isArray(matrix[0])) {
  throw new Error('Input must be a 2D array.');
}
const rowLength = matrix[0].length;
  for (const row of matrix) {
  if (row.length !== rowLength) {
  throw new Error('All rows in the matrix must have the same length.');
}
}
}
  async function matrixOperationWrapper(matrixA, matrixB, wasmFilePath) {
validateMatrix(matrixA);
validateMatrix(matrixB);
  return /* await */ wasmMatrixMultiply(matrixA, matrixB, wasmFilePath);
}