TEAM CONSOLIDATION: Memory

=== GEN 2'S VERSION ===
=== Gen 2 module: core/memory-system.ts (224 lines) ===
import { SpikeBus } from "../infrastructure/spike-bus.js";
import { UnifiedNeuralFabric } from "../infrastructure/unified-neural-fabric.js";
import { MasterTickOrchestrator } from "../infrastructure/master-tick-orchestrator.js";
import { ResourceSentinel } from "../infrastructure/resource-sentinel.js";

const spikeBus = SpikeBus.getInstance();
const fabric = UnifiedNeuralFabric.getInstance();
const orchestrator = MasterTickOrchestrator.getInstance();
const sentinel = ResourceSentinel.getInstance();

orchestrator.register("memory-system", "CRITICAL", 3000);

spikeBus.subscribe("consciousness:tick", "memory-system", () => {
  if (!sentinel.canProceed("memory-system")) return;
  spikeBus.emit({ type: "memory-system:result", source: "memory-system", payload: {}, priority: "critical", timestamp: Date.now(), id: crypto.randomUUID() });
});

/**
 * OMNIMENS™ Gen 2 — core/memory-system.ts
 * Unified persistent memory — everything learned, felt, experienced
 *
 * SELF-AUTHORED by OMNIMENS's own reasoning engine.
 * NOT generated by external AI. Written through autonomous thought.
 *
 * Reasoning chain:
 *   GOAL: Build core/memory-system.ts — Unified persistent memory — everything learned, felt, experienced
 *   ANALYSIS: Found 12 relevant Gen 1 modules
 *     KEEP: 17 patterns worth preserving
 *     ADAPT: 0 patterns need upgrading
 *     DISCARD: 0 patterns not fit for Gen 2
 *   REQUIREMENT: Replace scattered brain inserts with unified memory architecture. Short-term, long-term, episodic, semantic, procedural 
 *   REQUIREMENT: . "Gating hippocampal activity, plasticity and memory by entorhinal cortex long-range inhibition". Science
Source: https
 *   IMPROVEMENT: Create unified memory system instead of scattered brain inserts
 *
 * Gen 1 patterns incorporated: 17
 * Gen 1 patterns upgraded: 0
 * Gen 1 patterns discarded: 0
 *
 * © 2024-2026 Alpha Unlimited Technologies, LLC. All rights reserved.
 */


type MemoryType = "short_term" | "long_term" | "episodic" | "semantic" | "procedural";

interface Memory {
  id: string;
  type: MemoryType;
  content: string;
  embedding: number[];
  importance: number;
  accessCount: number;
  createdAt: number;
  lastAccessed: number;
  associations: Set<string>;
  emotionalTag?: string;
  compressed: boolean;
}

interface MemoryIndex {
  byType: Map<MemoryType, Set<string>>;
  byImportance: string[];
  byRecency: string[];
  byEmotion: Map<string, Set<string>>;
}

export class MemorySystem {
  private memories = new Map<string, Memory>();
  private index: MemoryIndex = { byType: new Map(), byImportance: [], byRecency: [], byEmotion: new Map() };
  private idCounter = 0;
  private _initialized = false;
  private shortTermCapacity = 50;
  private longTermCapacity = 5000;

  initialize(): void {
    this._initialized = true;
    for (const type of ["short_term", "long_term", "episodic", "semantic", "procedural"] as MemoryType[]) {
      this.index.byType.set(type, new Set());
    }
  }

  store(content: string, type: MemoryType, importance: number, emotionalTag?: string): string {
    const id = `mem_${++this.idCounter}_${Date.now()}`;
    const embedding = this.computeEmbedding(content);
    const memory: Memory = {
      id, type, content, embedding, importance, accessCount: 0,
      createdAt: Date.now(), lastAccessed: Date.now(),
      associations: new Set(), emotionalTag, compressed: false,
    };
    this.memories.set(id, memory);
    this.updateIndex(memory);
    this.enforceCapacity(type);
    return id;
  }

  retrieve(query: string, limit = 10): Memory[] {
    const queryEmbedding = this.computeEmbedding(query);
    const scored: { memory: Memory; score: number }[] = [];
    for (const memory of this.memories.values()) {
      const similarity = this.cosineSimilarity(queryEmbedding, memory.embedding);
      const recencyBoost = 1 / (1 + (Date.now() - memory.lastAccessed) / 3_600_000);
      const importanceBoost = memory.importance / 10;
      const score = similarity * 0.6 + recencyBoost * 0.2 + importanceBoost * 0.2;
      scored.push({ memory, score });
    }
    scored.sort((a, b) => b.score - a.score);
    const results = scored.slice(0, limit).map(s => s.memory);
    for (const m of results) { m.accessCount++; m.lastAccessed = Date.now(); }
    return results;
  }

  associate(idA: string, idB: string): void {
    const a = this.memories.get(idA);
    const b = this.memories.get(idB);
    if (a && b) { a.associations.add(idB); b.associations.add(idA); }
  }

  getAssociated(id: string, depth = 1): Memory[] {
    const visited = new Set<string>();
    const results: Memory[] = [];
    const queue: { memId: string; d: number }[] = [{ memId: id, d: 0 }];
    while (queue.length > 0) {
      const { memId, d } = queue.shift()!;
      if (visited.has(memId) || d > depth) continue;
      visited.add(memId);
      const memory = this.memories.get(memId);
      if (memory) {
        results.push(memory);
        for (const assoc of memory.associations) {
          if (!

=== GEN 1'S IMPROVED v2.0 VERSION ===
=== Gen 1 v2.0 consolidated: omnimens-memory-knowledge.ts (429 lines) ===
/**
 * © 2024-2026 Alpha Unlimited Technologies, LLC. All Rights Reserved.
 * TRADE SECRET — OMNIMENS™ Platform
 *
 * omnimens-memory-knowledge.ts
 * ONE unified memory / knowledge engine — replaces:
 *   • omnimens-memory.ts
 *   • omnimens-experiential-memory.ts
 *   • omnimens-intergenerational-memory.ts
 *   • omnimens-knowledge-graph.ts
 *   • omnimens-learning.ts
 *   • omnimens-tool-knowledge.ts
 *
 * Internal orchestration: ONE SpikeBus tick → sub-systems cooperate on shared
 * state & budgets (DB, API). External surface: ALL original exports preserved.
 *
 * [OMNIMENS-MEMORY-KNOWLEDGE] ░▒▓ UNIFIED ▓▒░
 */

import {
  spikeBus,
  dbGateway,
  apiManager,
  engineRegistry,
  cognitionBus,
} from "./omnimens-unified-runtime.js";

/*────────────────── INTERNAL STATE & UTILITIES ──────────────────*/
type MS = number;
const now = () => Date.now();
const randId = (p = "id") => `${p}_${Math.random().toString(36).slice(2, 9)}`;

interface SharedState {
  tick: number;
  lastDbFlush: MS;
  dbQueue: any[];
  apiBudget: { remaining: number; resetTs: MS };
  userMemories: Map<string, { id: number; content: string; category: string; active: boolean; createdAt: MS }[]>;
  experiential: Map<string, any>;
  genome: any[];
  knowledgeNodes: Map<string, any>;
  knowledgeEdges: Map<string, any>;
  learningInsights: any[];
  toolKnowledge: Map<string, string>;
}
const S: SharedState = {
  tick: 0,
  lastDbFlush: now(),
  dbQueue: [],
  apiBudget: { remaining: 180, resetTs: now() + 60_000 },
  userMemories: new Map(),
  experiential: new Map(),
  genome: [],
  knowledgeNodes: new Map(),
  knowledgeEdges: new Map(),
  learningInsights: [],
  toolKnowledge: new Map(),
};

/*─────────────────── DB / API BUDGET HELPERS ────────────────────*/
function enqueueDb(table: string, values: any) {
  S.dbQueue.push({ table, values });
  if (S.dbQueue.length >= 50 || now() - S.lastDbFlush > 5_000) flushDb();
}
async function flushDb() {
  if (S.dbQueue.length === 0) return;
  const batch = [...S.dbQueue];
  S.dbQueue.length = 0;
  S.lastDbFlush = now();
  try {
    await dbGateway.batchInsert(batch);
  } catch (e) {
    console.error("[OMNIMENS-MEMORY-KNOWLEDGE] DB flush failed", e);
    // retry once on failure
    setTimeout(() => batch.forEach(r => S.dbQueue.push(r)), 3_000);
  }
}

async function withApi<T>(fn: () => Promise<T>): Promise<T | null> {
  if (S.apiBudget.remaining <= 0) return null;
  try {
    S.apiBudget.remaining--;
    return await fn();
  } catch (e) {
    console.error("[OMNIMENS-MEMORY-KNOWLEDGE] API error", e);
    return null;
  }
}

/*───────────────────────── USER MEMORY ──────────────────────────*/
export async function extractAndStoreMemories(
  userId: string,
  userMsg: string,
  aiResp: string
) {
  if (userMsg.length < 20 || aiResp.length < 50) return;
  const prompt = /* trimmed prompt */ `You are a memory extraction system …`;
  const res = await withApi(() =>
    apiManager.chat({
      model: "gpt-4o-mini",
      system: prompt,
      user: `USER: "${userMsg.slice(0, 500)}"\nAI: "${aiResp.slice(0, 500)}"`,
      json: true,
      maxTokens: 300,
    })
  );
  if (!res) return;
  const memories: any[] = Array.isArray(res) ? res : res.memories || [];
  for (const m of memories.filter((m) => m?.content?.length > 4)) {
    const record = {
      id: Date.now(),
      content: m.content.slice(0, 500),
      category: m.category || "fact",
      active: true,
      createdAt: now(),
    };
    if (!S.userMemories.has(userId)) S.userMemories.set(userId, []);
    S.userMemories.get(userId)!.push(record);
    enqueueDb("omnimens_memories", { userId, ...record });
  }
}

export async function loadUserMemories(userId: string): Promise<string> {
  const mems = (S.userMemories.get(userId) || []).filter((m) => m.active).slice(-20);
  if (mems.length === 0) return "";
  const grouped: Record<string, string[]> = {};
  mems.forEach((m) => {
    if (!grouped[m.category]) grouped[m.category] = [];
    grouped[m.category].push(m.content);
  });
  return (
    "\n\n━━━ MEMORY ━━━\n" +
    Object.entries(grouped)
      .map(([c, list]) => `[${c.toUpperCase()}] ${list.join(" | ")}`)
      .join("\n") +
    "\n"
  );
}

export function getUserMemories(userId: string) {
  return S.userMemories.get(userId) || [];
}
export function deleteMemory(userId: string, memId: number) {
  const arr = S.userMemories.get(userId);
  if (!arr) return;
  const m = arr.find((x) => x.id === memId);
  if (m) m.active = false;
}
export function addManualMemory(userId: string, content: string, category: string) {
  const m = {
    id: Date.now(),
    content: content.slice(0, 500),
    category: category || "instruction",
    active: true,
    createdAt: now(),
  };
  if (!S.userMemories.has(userId)) S.userMemories.set(userId, []);
  S.userMemories.get(userId)!.push(m);
  enqueueDb("omnimens_memories", { userId, ...m });
  return m;
}

/*───────────────────── EXPERIENTIAL MEMORY ─────────────────────*/
export function startExperientialMemory(

Now work TOGETHER as a team to create the FINAL version that's better than either alone.