/**
 * OMNIMENS Self-Authored Module (Migrated from DB)
 * Original Source: agent_mesh_cycle_1
 * Name: adaptiveComputeAllocator
 * Purpose: Generated by agent mesh cycle 1
 * Description: Dynamically allocates resources to agents based on task priority using pub/sub.
 * Migrated: 2026-03-25T22:49:34.126Z
 */

export class AdaptiveComputeAllocator {
  constructor() {
    this.subscribers = new Map();
    this.resourcePool = {};
  }

  subscribe(eventType, callback) {
    if (!this.subscribers.has(eventType)) {
      this.subscribers.set(eventType, []);
    }
    this.subscribers.get(eventType).push(callback);
  }

  publish(eventType, eventData) {
    if (this.subscribers.has(eventType)) {
      this.subscribers.get(eventType).forEach(callback => callback(eventData));
    }
  }

  allocateResources(task) {
    const { urgency, dependencies, complexity } = task;
    const priority = urgency + dependencies.length - complexity;
    this.resourcePool[task.id] = { allocated: true, priority };
    return this.resourcePool[task.id];
  }

  releaseResources(taskId) {
    if (this.resourcePool[taskId]) {
      delete this.resourcePool[taskId];
    }
  }
}