/**
 * OMNIMENS Self-Authored Module (Migrated from DB)
 * Original Source: agent_mesh_cycle_1
 * Name: applyGestaltVisualization
 * Purpose: Generated by agent mesh cycle 1
 * Description: Formats reasoning outputs using Gestalt principles for visual clarity and accessibility.
 * Migrated: 2026-03-25T22:49:34.152Z
 */

export function applyGestaltVisualization(data) {
  const formattedData = data.map(item => ({
    ...item,
    visualHierarchy: {
      proximity: item.proximityGroup,
      similarity: item.similarityGroup,
      closure: item.isClosed
    }
  }));

  return formattedData;
}