/**
 * OMNIMENS Self-Authored Module (Migrated from DB)
 * Original Source: agent_mesh_cycle_1
 * Name: confidenceCalibratedCompute
 * Purpose: Generated by agent mesh cycle 1
 * Description: Implements a confidence-calibrated compute allocation mechanism using a pub/sub system.
 * Migrated: 2026-03-25T22:49:34.145Z
 */

export class ConfidenceCalibratedCompute {
  constructor() {
    this.subscribers = new Map();
  }

  subscribe(event, callback) {
    if (!this.subscribers.has(event)) {
      this.subscribers.set(event, []);
    }
    this.subscribers.get(event).push(callback);
  }

  publish(event, data) {
    const callbacks = this.subscribers.get(event) || [];
    callbacks.forEach(callback => callback(data));
  }

  allocateResources(taskList) {
    taskList.sort((a, b) => b.confidence - a.confidence);
    return taskList.map(task => {
      const allocatedResources = Math.min(task.requiredResources, task.confidence * 100);
      return { ...task, allocatedResources };
    });
  }
}

// Example Usage
const computeAllocator = new ConfidenceCalibratedCompute();
computeAllocator.subscribe('taskCompleted', data => {
  console.log('Task completed:', data);
});

const tasks = [
  { id: 1, confidence: 0.9, requiredResources: 50 },
  { id: 2, confidence: 0.6, requiredResources: 30 },
  { id: 3, confidence: 0.7, requiredResources: 40 }
];

const allocated = computeAllocator.allocateResources(tasks);
console.log(allocated);