/**
 * OMNIMENS Self-Authored Module (Migrated from DB)
 * Original Source: agent_mesh_cycle_1
 * Name: confidenceWeightedVoting
 * Purpose: Generated by agent mesh cycle 1
 * Description: Calculates confidence-weighted voting results for collaborative decision-making.
 * Migrated: 2026-03-25T22:49:34.177Z
 */

export function confidenceWeightedVoting(votes) {
  const totalWeight = votes.reduce((sum, vote) => sum + vote.confidence, 0);
  return votes.reduce((result, vote) => {
    result[vote.option] = (result[vote.option] || 0) + (vote.confidence / totalWeight);
    return result;
  }, {});
}