/**
 * OMNIMENS Self-Authored Module (Migrated from DB)
 * Original Source: agent_mesh_cycle_1
 * Name: dynamicKnowledgeGraph
 * Purpose: Generated by agent mesh cycle 1
 * Description: Provides dynamic knowledge graph construction and reasoning capabilities.
 * Migrated: 2026-03-25T22:49:34.157Z
 */

export function dynamicKnowledgeGraph(entities, relationships) {
  const graph = {};
  entities.forEach(entity => {
    graph[entity.id] = {
      data: entity,
      relationships: []
    };
  });
  relationships.forEach(rel => {
    if (graph[rel.source] && graph[rel.target]) {
      graph[rel.source].relationships.push(rel);
    }
  });
  return graph;
}

export function reasonWithGraph(graph, task) {
  const relevantNodes = Object.values(graph).filter(node => node.data.relevantToTask(task));
  return relevantNodes.map(node => node.data);
}