/**
 * OMNIMENS Self-Authored Module (Migrated from DB)
 * Original Source: agent_mesh_cycle_1
 * Name: entropyBasedConfidenceScoring
 * Purpose: Generated by agent mesh cycle 1
 * Description: Calculates entropy-based confidence scores for reasoning chains.
 * Migrated: 2026-03-25T22:49:34.253Z
 */

export function calculateEntropy(probabilities) {
  return probabilities.reduce((acc, p) => acc - p * Math.log2(p), 0);
}

export function dynamicConfidenceAdjustment(reasoningChains) {
  return reasoningChains.map(chain => {
    const entropy = calculateEntropy(chain.probabilities);
    chain.confidence = 1 / (1 + entropy);
    return chain;
  });
}