/**
 * OMNIMENS Self-Authored Module (Migrated from DB)
 * Original Source: agent_mesh_cycle_1
 * Name: entropySelfConsistencyScoring
 * Purpose: Generated by agent mesh cycle 1
 * Description: Provides entropy-based scoring to evaluate the coherence of reasoning chains.
 * Migrated: 2026-03-25T22:49:34.218Z
 */

export class EntropyScoring {
  static calculateEntropy(probabilities) {
    return -probabilities.reduce((acc, p) => acc + (p > 0 ? p * Math.log2(p) : 0), 0);
  }

  static scoreReasoningChain(chain) {
    const probabilities = chain.map(node => node.probability || 0.5); // Default probability if not provided
    return this.calculateEntropy(probabilities);
  }

  static isConsistent(chain, threshold) {
    const entropy = this.scoreReasoningChain(chain);
    return entropy <= threshold;
  }
}