/**
 * OMNIMENS Self-Authored Module (Migrated from DB)
 * Original Source: agent_mesh_cycle_1
 * Name: hierarchicalTaskDelegation
 * Purpose: Generated by agent mesh cycle 1
 * Description: Provides dynamic hierarchical task delegation based on priority and complexity.
 * Migrated: 2026-03-25T22:49:34.179Z
 */

export class HierarchicalTaskDelegation {
  constructor() {
    this.taskQueue = [];
    this.agentPool = [];
  }

  addTask(task) {
    this.taskQueue.push(task);
    this.delegateTasks();
  }

  addAgent(agent) {
    this.agentPool.push(agent);
  }

  delegateTasks() {
    this.taskQueue.sort((a, b) => b.priority - a.priority);
    for (const task of this.taskQueue) {
      const suitableAgent = this.agentPool.find(agent => agent.canHandle(task));
      if (suitableAgent) {
        suitableAgent.assignTask(task);
        this.taskQueue = this.taskQueue.filter(t => t !== task);
      }
    }
  }
}