/**
 * OMNIMENS Self-Authored Module (Migrated from DB)
 * Original Source: agent_mesh_cycle_1
 * Name: stdpLearningModule
 * Purpose: Generated by agent mesh cycle 1
 * Description: Introduces STDP-based learning for improved memory consolidation.
 * Migrated: 2026-03-25T22:49:34.153Z
 */

export function applySTDP(preSynapticSpike, postSynapticSpike, weight) {
  const deltaT = postSynapticSpike.time - preSynapticSpike.time;
  const learningRate = 0.01;

  if (deltaT > 0) {
    // Long-term potentiation (LTP)
    return weight + learningRate * Math.exp(-deltaT);
  } else {
    // Long-term depression (LTD)
    return weight - learningRate * Math.exp(deltaT);
  }
}

export function consolidateMemory(synapticConnections, spikeHistory) {
  synapticConnections.forEach(connection => {
    const preSpike = spikeHistory.find(spike => spike.id === connection.preSynaptic);
    const postSpike = spikeHistory.find(spike => spike.id === connection.postSynaptic);

    if (preSpike && postSpike) {
      connection.weight = applySTDP(preSpike, postSpike, connection.weight);
    }
  });
}