/**
 * OMNIMENS Self-Authored Module (Migrated from DB)
 * Original Source: agent_mesh_cycle_1
 * Name: stdpTemporalLearning
 * Purpose: Generated by agent mesh cycle 1
 * Description: Implements STDP-based synaptic learning to refine temporal alignment in memory consolidation.
 * Migrated: 2026-03-25T22:49:34.155Z
 */

export const stdpTemporalLearning = (neurons, spikeTimings) => {
  const learningRate = 0.01;
  neurons.forEach((neuron, index) => {
    const deltaTime = spikeTimings[index + 1] - spikeTimings[index];
    if (deltaTime > 0) {
      neuron.synapticWeights += learningRate * deltaTime;
    } else {
      neuron.synapticWeights -= learningRate * Math.abs(deltaTime);
    }
  });
  return neurons;
};