/**
 * OMNIMENS Self-Authored Module (Migrated from DB)
 * Original Source: agent_mesh_cycle_1
 * Name: weightedConfidenceVoting
 * Purpose: Generated by agent mesh cycle 1
 * Description: Aggregates agent outputs using weighted confidence voting to resolve conflicts.
 * Migrated: 2026-03-25T22:49:34.162Z
 */

export function weightedConfidenceVoting(agentOutputs) {
  const weightedScores = agentOutputs.map(output => {
    const weight = output.agentConfidence;
    return { output: output.data, weightedScore: weight * output.score };
  });

  const aggregatedOutput = weightedScores.reduce((acc, item) => {
    acc[item.output] = (acc[item.output] || 0) + item.weightedScore;
    return acc;
  }, {});

  const sortedOutputs = Object.entries(aggregatedOutput).sort((a, b) => b[1] - a[1]);

  return sortedOutputs[0][0];
}
