/**
 * OMNIMENS Self-Authored Module (Migrated from DB)
 * Original Source: agent_mesh_cycle_1
 * Name: bayesianUncertaintyQuantification
 * Purpose: Generated by agent mesh cycle 1
 * Description: Adds Bayesian uncertainty quantification for dynamic reasoning chain evaluation.
 * Migrated: 2026-03-25T22:49:34.149Z
 */

export const bayesianUncertaintyQuantification = {
  calculateEntropy: function(probabilities) {
    return probabilities.reduce((acc, p) => acc - p * Math.log2(p), 0);
  },
  updateConfidence: function(chain, feedback) {
    const entropy = this.calculateEntropy(chain.map(step => step.probability));
    const adjustmentFactor = feedback === 'positive' ? -0.1 : 0.1;
    chain.forEach(step => {
      step.probability = Math.min(Math.max(step.probability + adjustmentFactor * entropy, 0), 1);
    });
  }
};