/**
 * OMNIMENS Self-Authored Module (Migrated from DB)
 * Original Source: agent_mesh_cycle_1
 * Name: confidenceWeightedSynthesis
 * Purpose: Generated by agent mesh cycle 1
 * Description: Confidence-weighted synthesis for multi-agent output resolution.
 * Migrated: 2026-03-25T22:49:34.228Z
 */

export function confidenceWeightedSynthesis(agentOutputs) {
  const weightedResults = {};

  agentOutputs.forEach(({ output, confidence }) => {
    for (const [key, value] of Object.entries(output)) {
      if (!weightedResults[key]) {
        weightedResults[key] = { total: 0, weight: 0 };
      }
      weightedResults[key].total += value * confidence;
      weightedResults[key].weight += confidence;
    }
  });

  const synthesizedOutput = {};
  for (const [key, { total, weight }] of Object.entries(weightedResults)) {
    synthesizedOutput[key] = total / weight;
  }

  return synthesizedOutput;
}

// Usage example:
// const outputs = [
//   { output: { a: 0.8, b: 0.5 }, confidence: 0.9 },
//   { output: { a: 0.7, b: 0.6 }, confidence: 0.8 }
// ];
// console.log(confidenceWeightedSynthesis(outputs));