/**
 * OMNIMENS Self-Authored Module (Migrated from DB)
 * Original Source: agent_mesh_cycle_1
 * Name: metaLearningRateManager
 * Purpose: Generated by agent mesh cycle 1
 * Description: Manages dynamic learning rate adjustment for modules based on system-wide metrics.
 * Migrated: 2026-03-25T22:49:34.130Z
 */

export class MetaLearningRateManager {
  constructor(metrics) {
    this.metrics = metrics;
    this.learningRates = {};
  }

  adjustLearningRates() {
    Object.keys(this.metrics).forEach(module => {
      const performance = this.metrics[module].performance;
      const resourceUsage = this.metrics[module].resourceUsage;
      this.learningRates[module] = this.calculateRate(performance, resourceUsage);
    });
  }

  calculateRate(performance, resourceUsage) {
    const baseRate = 0.01;
    const adjustmentFactor = Math.max(1 - resourceUsage / 100, 0.1);
    return baseRate * adjustmentFactor * (1 + performance / 100);
  }

  getLearningRate(module) {
    return this.learningRates[module] || 0.01;
  }
}